function [ret,x0,str,ts,xts]=asknrzbw(t,x,u,flag);
%ASKNRZBW	is the M-file description of the SIMULINK system named ASKNRZBW.
%	The block-diagram can be displayed by typing: ASKNRZBW.
%
%	SYS=ASKNRZBW(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes ASKNRZBW to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling ASKNRZBW with a FLAG of zero:
%	[SIZES]=ASKNRZBW([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = mfilename;
new_system(sys)
simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[196,42,1260,318])
     open_system(sys)
end;
set_param(sys,'algorithm',     'RK-45')
set_param(sys,'Start time',    '0.0')
set_param(sys,'Stop time',     '999999')
set_param(sys,'Min step size', '.000001')
set_param(sys,'Max step size', '10')
set_param(sys,'Relative error','1e-3')
set_param(sys,'Return vars',   '')


%     Subsystem  'Kanal'.

new_system([sys,'/','Kanal'])
set_param([sys,'/','Kanal'],'Location',[11,262,273,408])

add_block('built-in/Inport',[sys,'/','Kanal/in_1'])
set_param([sys,'/','Kanal/in_1'],...
		'position',[45,10,65,30])

add_block('built-in/Outport',[sys,'/','Kanal/out_1'])
set_param([sys,'/','Kanal/out_1'],...
		'position',[200,55,220,75])

add_block('built-in/Sum',[sys,'/','Kanal/Sum'])
set_param([sys,'/','Kanal/Sum'],...
		'position',[150,55,170,75])


%     Subsystem  ['Kanal/Gaussian noise',13,'generator'].

new_system([sys,'/',['Kanal/Gaussian noise',13,'generator']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],'Location',[22,119,370,243])

add_block('built-in/State-Space',[sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'Mask Display','K',...
		'Mask Type','Matrix Gain',...
		'Mask Dialogue','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'Mask Translate','K = @1;',...
		'Mask Help','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'Mask Entries','d\/')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'position',[140,61,165,89])

add_block('built-in/White Noise',[sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']],...
		'Seed','s',...
		'position',[35,57,80,93])

add_block('built-in/Constant',[sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']],...
		'Value','m',...
		'position',[140,20,160,40])

add_block('built-in/Sum',[sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']],...
		'position',[220,60,240,80])

add_block('built-in/Outport',[sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']],...
		'position',[285,60,305,80])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[165,30;190,30;190,65;215,65])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[245,70;280,70])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[170,75;215,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[85,75;135,75])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Display','plot(0,0,100,100,x,y);Gaussian',...
		'Mask Type','Gaussian noise generator')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Dialogue','Generate Gaussian distributed noise with\ngiven mean and variance value.|Mean value:|Variance (vector or matrix):|Initial seed:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=srcsicon(3);')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Help','When the mean value and seed are vectors, the output of this block is a vector. The length of the vector is the same as the length of the mean value vector or the length of the seed. When the variance entry is a vector, the variance is a diagonal matrix.')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Entries','m\/d\/s\/')


%     Finished composite block ['Kanal/Gaussian noise',13,'generator'].

set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'position',[25,48,105,92])
add_line([sys,'/','Kanal'],[175,65;195,65])
add_line([sys,'/','Kanal'],[70,20;115,20;115,60;145,60])
add_line([sys,'/','Kanal'],[110,70;145,70])
set_param([sys,'/','Kanal'],...
		'Mask Display','plot(0,0,100,100,x,y);AWGN',...
		'Mask Type','AWGN channel, fixed parameter')
set_param([sys,'/','Kanal'],...
		'Mask Dialogue','Additive white Gaussian noise channel\nwith fixed mean and variance.|Mean value:|Variance (std^2):|Initial Seed:',...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=chanicon;')
set_param([sys,'/','Kanal'],...
		'Mask Help','This block adds white Gaussian noise to the input signal. The mean and the variance can be a scalar or vector with the same length as the input signal.',...
		'Mask Entries','0\/.001\/12345\/')


%     Finished composite block 'Kanal'.

set_param([sys,'/','Kanal'],...
		'position',[480,113,560,157])


%     Subsystem  'MASK map'.

new_system([sys,'/','MASK map'])
set_param([sys,'/','MASK map'],'Location',[520,162,902,335])

add_block('built-in/Constant',[sys,'/','MASK map/Gain diff'])
set_param([sys,'/','MASK map/Gain diff'],...
		'Value','Ac',...
		'position',[180,96,215,124])

add_block('built-in/Sum',[sys,'/','MASK map/Sum1'])
set_param([sys,'/','MASK map/Sum1'],...
		'inputs','+-',...
		'position',[250,63,270,87])

add_block('built-in/Gain',[sys,'/','MASK map/Gain'])
set_param([sys,'/','MASK map/Gain'],...
		'Gain','Kc',...
		'position',[180,25,220,55])

add_block('built-in/Inport',[sys,'/','MASK map/in_1'])
set_param([sys,'/','MASK map/in_1'],...
		'position',[40,30,60,50])

add_block('built-in/Zero-Order Hold',[sys,'/',['MASK map/Zero-Order',13,'Hold']])
set_param([sys,'/',['MASK map/Zero-Order',13,'Hold']],...
		'Sample time','td',...
		'position',[100,24,135,56])

add_block('built-in/Outport',[sys,'/','MASK map/out_1'])
set_param([sys,'/','MASK map/out_1'],...
		'position',[315,65,335,85])
add_line([sys,'/','MASK map'],[140,40;175,40])
add_line([sys,'/','MASK map'],[65,40;95,40])
add_line([sys,'/','MASK map'],[275,75;310,75])
add_line([sys,'/','MASK map'],[220,110;230,110;230,80;245,80])
add_line([sys,'/','MASK map'],[225,40;230,40;230,70;245,70])
set_param([sys,'/','MASK map'],...
		'Mask Display','MASK\nmap',...
		'Mask Type','MASK map')
set_param([sys,'/','MASK map'],...
		'Mask Dialogue','Map a digital symbol onto an analog\nsignal in the range [-1, 1] using M-ary\namplitude shift keying modulation mapping.|M-ary number (input integers in range [0, M-1]):|Input symbol interval and offset (sec):')
set_param([sys,'/','MASK map'],...
		'Mask Translate','N=@1;Ac=1;Kc=Ac*2/(N-1);td=@2;')
set_param([sys,'/','MASK map'],...
		'Mask Help','This block maps an input digit signal onto a signal in the range [-1, 1]. The coded signal can be modulated using analog\nmodulation blocks. Input digits are in the range [0, M-1], where M is the M-ary number. The input symbol interval can be a two-element vector with the second element being offset. The default value offset is 0. Use the MODMAP function to see the constellation.')
set_param([sys,'/','MASK map'],...
		'Mask Entries','4\/1\/')


%     Finished composite block 'MASK map'.

set_param([sys,'/','MASK map'],...
		'position',[120,103,200,147])

add_block('built-in/Product',[sys,'/','Product'])
set_param([sys,'/','Product'],...
		'hide name',0,...
		'position',[380,117,405,148])

add_block('built-in/Scope',[sys,'/','Sendesignal s(t)'])
set_param([sys,'/','Sendesignal s(t)'],...
		'orientation',1,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[357,631,1280,731])
open_system([sys,'/','Sendesignal s(t)'])
set_param([sys,'/','Sendesignal s(t)'],...
		'position',[420,225,450,255])

add_block('built-in/Scope',[sys,'/','Empfangssignal r(t)'])
set_param([sys,'/','Empfangssignal r(t)'],...
		'orientation',1,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[356,729,1280,829])
open_system([sys,'/','Empfangssignal r(t)'])
set_param([sys,'/','Empfangssignal r(t)'],...
		'position',[575,225,605,255])

add_block('built-in/Scope',[sys,'/','x(t)'])
set_param([sys,'/','x(t)'],...
		'orientation',1,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[357,532,1280,632])
open_system([sys,'/','x(t)'])
set_param([sys,'/','x(t)'],...
		'position',[210,225,240,255])

add_block('built-in/Fcn',[sys,'/','Fcn'])
set_param([sys,'/','Fcn'],...
		'hide name',0,...
		'Expr','cos(4*pi*u)',...
		'position',[285,162,355,188])

add_block('built-in/Clock',[sys,'/','Clock'])
set_param([sys,'/','Clock'],...
		'position',[245,165,265,185])

add_block('built-in/Scope',[sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[357,436,1280,536])
open_system([sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'position',[120,225,150,255])

add_block('built-in/Fcn',[sys,'/','Fcn1'])
set_param([sys,'/','Fcn1'],...
		'hide name',0,...
		'Expr','2*cos(4*pi*u)',...
		'position',[535,17,630,43])

add_block('built-in/Clock',[sys,'/','Clock1'])
set_param([sys,'/','Clock1'],...
		'position',[495,20,515,40])

add_block('built-in/Scope',[sys,'/','Senkensignal v(t)'])
set_param([sys,'/','Senkensignal v(t)'],...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[356,924,1280,1024])
open_system([sys,'/','Senkensignal v(t)'])
set_param([sys,'/','Senkensignal v(t)'],...
		'position',[995,115,1025,145])

add_block('built-in/Scope',[sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'orientation',1,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[356,828,1280,928])
open_system([sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'position',[825,185,855,215])


%     Subsystem  'Error rate'.

new_system([sys,'/','Error rate'])
set_param([sys,'/','Error rate'],'Location',[255,368,509,510])

add_block('built-in/Inport',[sys,'/','Error rate/in_2'])
set_param([sys,'/','Error rate/in_2'],...
		'Port','2',...
		'position',[15,60,35,80])

add_block('built-in/Inport',[sys,'/','Error rate/in_1'])
set_param([sys,'/','Error rate/in_1'],...
		'position',[15,45,35,65])

add_block('built-in/Mux',[sys,'/','Error rate/Mux'])
set_param([sys,'/','Error rate/Mux'],...
		'inputs','2',...
		'position',[65,46,100,79])

add_block('built-in/S-Function',[sys,'/','Error rate/S-function'])
set_param([sys,'/','Error rate/S-function'],...
		'function name','sbiterr',...
		'parameters','num_lin, K, TDelay, Sample',...
		'position',[130,52,195,78])
add_line([sys,'/','Error rate'],[40,70;60,70])
add_line([sys,'/','Error rate'],[40,55;60,55])
add_line([sys,'/','Error rate'],[105,65;125,65])
set_param([sys,'/','Error rate'],...
		'Mask Display','Error\nmeter',...
		'Mask Type','Symbol/bit error counter')
set_param([sys,'/','Error rate'],...
		'Mask Dialogue','Use the input data from the 1st port as the reference signal to detect the number of errors and error rate of the 2nd signal.|Bit per symbol:|Number of digits on display:|Delay between 1st port and 2nd port:|Sample time (sec):')
set_param([sys,'/','Error rate'],...
		'Mask Translate','K=@1;num_lin=@2;TDelay=@3;Sample=@4;')
set_param([sys,'/','Error rate'],...
		'Mask Help','The signal from the first port must be a scalar. The second input port can be a vector with a delay to the first port signal. The comparison happens only at the sampling point.')
set_param([sys,'/','Error rate'],...
		'Mask Entries','2\/10\/1\/1\/')


%     Finished composite block 'Error rate'.

set_param([sys,'/','Error rate'],...
		'orientation',1,...
		'position',[910,225,990,265])


%     Subsystem  'MASK demap'.

new_system([sys,'/','MASK demap'])
set_param([sys,'/','MASK demap'],'Location',[187,342,628,482])

add_block('built-in/Zero-Order Hold',[sys,'/',['MASK demap/Zero-Order',13,'Hold']])
set_param([sys,'/',['MASK demap/Zero-Order',13,'Hold']],...
		'Sample time','td',...
		'position',[85,29,120,61])

add_block('built-in/Constant',[sys,'/','MASK demap/Shift key'])
set_param([sys,'/','MASK demap/Shift key'],...
		'Value','sft',...
		'position',[115,93,135,117])

add_block('built-in/Sum',[sys,'/','MASK demap/Sum2'])
set_param([sys,'/','MASK demap/Sum2'],...
		'inputs','+-',...
		'position',[180,38,200,67])

add_block('built-in/Abs',[sys,'/','MASK demap/Abs'])
set_param([sys,'/','MASK demap/Abs'],...
		'position',[235,42,270,68])

add_block('built-in/Outport',[sys,'/','MASK demap/out_1'])
set_param([sys,'/','MASK demap/out_1'],...
		'position',[400,45,420,65])

add_block('built-in/S-Function',[sys,'/','MASK demap/Minimum'])
set_param([sys,'/','MASK demap/Minimum'],...
		'function name','arymimai',...
		'parameters','''min''',...
		'position',[315,45,370,65])

add_block('built-in/Inport',[sys,'/','MASK demap/in_1'])
set_param([sys,'/','MASK demap/in_1'],...
		'position',[30,35,50,55])
add_line([sys,'/','MASK demap'],[55,45;80,45])
add_line([sys,'/','MASK demap'],[275,55;310,55])
add_line([sys,'/','MASK demap'],[125,45;175,45])
add_line([sys,'/','MASK demap'],[375,55;395,55])
add_line([sys,'/','MASK demap'],[140,105;155,105;155,60;175,60])
add_line([sys,'/','MASK demap'],[205,55;230,55])
set_param([sys,'/','MASK demap'],...
		'Mask Display','MASK\ndemap',...
		'Mask Type','MASK demap')
set_param([sys,'/','MASK demap'],...
		'Mask Dialogue','Reverse the MASK mapping process\nConvert [-1 1] analog signal to [0, M-1] symbols.|M-ary number (digit integers in ranger [0, M-1]):|Output symbol interval and offset (sec):')
set_param([sys,'/','MASK demap'],...
		'Mask Translate','N=@1;Ac=1;sft=[0:N-1]*Ac*2/(N-1)-Ac;td=@2;')
set_param([sys,'/','MASK demap'],...
		'Mask Help','This block demaps a MASK mapped signal back to digit symbols. You can place this block after a amplitude demodulation block. The input of this block is an analog signal in the range [-1, 1]. The demodulation decides the closest integer fitting in [0,M-1] range. When the input symbol interval is a two-elements vector, the second element is offset. The default offset value is 0.')
set_param([sys,'/','MASK demap'],...
		'Mask Entries','4\/[1, .9]\/')


%     Finished composite block 'MASK demap'.

set_param([sys,'/','MASK demap'],...
		'position',[870,108,950,152])

add_block('built-in/Product',[sys,'/','Product1'])
set_param([sys,'/','Product1'],...
		'hide name',0,...
		'position',[660,112,685,143])

add_block('built-in/Scope',[sys,'/',['Binäres',13,'Datensignal']])
set_param([sys,'/',['Binäres',13,'Datensignal']],...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[357,337,1280,437])
open_system([sys,'/',['Binäres',13,'Datensignal']])
set_param([sys,'/',['Binäres',13,'Datensignal']],...
		'position',[175,20,205,50])


%     Subsystem  ['ASK Mo//Dem',13,'demo1'].

new_system([sys,'/',['ASK Mo//Dem',13,'demo1']])
set_param([sys,'/',['ASK Mo//Dem',13,'demo1']],'Location',[175,552,335,697])
set_param([sys,'/',['ASK Mo//Dem',13,'demo1']],...
		'Mask Display','Signalraum-\nKonstellation',...
		'Mask Dialogue','eval(''figure''); eval(''modmap(''''ask'''',4)'')')


%     Finished composite block ['ASK Mo//Dem',13,'demo1'].

set_param([sys,'/',['ASK Mo//Dem',13,'demo1']],...
		'BackGround',7,...
		'hide name',0,...
		'position',[10,18,90,62])

add_block('built-in/Zero-Pole',[sys,'/',['Analog Butterworth',13,'LP Filter']])
set_param([sys,'/',['Analog Butterworth',13,'LP Filter']],...
		'Zeros','z',...
		'Poles','p',...
		'Gain','k',...
		'Mask Display','plot(20*log10(w),20*log10(abs(h)))',...
		'Mask Type','buttap')
set_param([sys,'/',['Analog Butterworth',13,'LP Filter']],...
		'Mask Dialogue','Analog Butterworth low pass filter.\n\n(Requires Signal Processing Toolbox)|Cutoff frequency (rad/sec)|Order')
set_param([sys,'/',['Analog Butterworth',13,'LP Filter']],...
		'Mask Translate','[z,p,k]=buttap(@2); z=@1*z; p=@1*p; k=real(prod(-p)); [num,den]=zp2tf(z,p,k); w=logspace(log10(@1/10),log10(10*@1),20); h=freqs(num,den,w); ')
set_param([sys,'/',['Analog Butterworth',13,'LP Filter']],...
		'Mask Help','Butterworth low pass filter using MATLAB''s butter command.',...
		'Mask Entries','5\/4\/',...
		'position',[730,108,790,152])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],'Location',[84,708,621,947])

add_block('built-in/Note',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Jeweils zwei Bits des Bitstroms werden zu einem quaternären Symbol decodiert.',13,'Reihenfolge der Bits: Zuerst MSB, dann LSB.']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Jeweils zwei Bits des Bitstroms werden zu einem quaternären Symbol decodiert.',13,'Reihenfolge der Bits: Zuerst MSB, dann LSB.']],...
		'position',[265,0,270,5])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],'Location',[12,432,357,702])

add_block('built-in/Digital Clock',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Digital Clock']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Digital Clock']],...
		'Sample time','ts',...
		'position',[60,140,95,170])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/in_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/in_1']],...
		'position',[20,80,40,100])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/out_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/out_1']],...
		'position',[325,120,345,140])

add_block('built-in/Filter',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/K-step',13,'delay']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/K-step',13,'delay']],...
		'Numerator','[zeros(1,n), 1]',...
		'Denominator','1',...
		'Sample time','ts',...
		'position',[60,70,185,110])

add_block('built-in/Switch',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Switch']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Switch']],...
		'Threshold','.1',...
		'position',[270,114,295,146])

add_block('built-in/Constant',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Constant']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Constant']],...
		'Value','ini',...
		'position',[120,230,140,250])

add_block('built-in/Constant',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Constant1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Constant1']],...
		'Value','n*ts(1)+ts(2)',...
		'position',[15,194,100,216])

add_block('built-in/Relational Operator',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Relational',13,'Operator']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung/Relational',13,'Operator']],...
		'position',[150,168,180,192])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[300,130;320,130])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[45,90;55,90])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[190,90;195,90;195,120;265,120])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[145,240;240,240;240,140;265,140])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[100,155;115,155;115,175;145,175])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[105,205;115,205;115,185;145,185])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],[185,180;220,180;220,130;265,130])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'Mask Display','    -k\nz   ',...
		'Mask Type','Multi-step delay')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'Mask Dialogue','Output is K-step delay of the input signal.|Delay steps (integer):|Sample time (sec):|Initial output:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'Mask Translate','n=@1;ts=@2;if length(ts)<2, ts=[ts 0];end;ini=@3;')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'Mask Help','This block holds the input signal for K steps and then outputs the signal. The delay step cannot be changed during the simulation.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'Mask Entries','2\/.5\/0\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Verzögerung']],...
		'position',[260,48,340,92])

add_block('built-in/S-Function',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/D//A Wandlung']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/D//A Wandlung']],...
		'function name','simbi2de',...
		'parameters','p',...
		'Mask Display','Vec to sca\nconverter',...
		'Mask Type','Base M vector to decimal integer')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/D//A Wandlung']],...
		'Mask Dialogue','Convert base M integer with each\nposition in the input vector into scalar decimal output.|Input integer base M:',...
		'Mask Translate','p=@1;')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/D//A Wandlung']],...
		'Mask Help','This block convert the base M vector into scalar decimal integer output. Each element of the input vector is one position of the digit of the base M integer. The 1st element in the input vector contains the 1''s position. The 2nd element in the input vector contains the M''s position.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/D//A Wandlung']],...
		'Mask Entries','2\/',...
		'position',[370,128,450,172])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],'Location',[22,58,460,228])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/out_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/out_1']],...
		'position',[390,60,410,80])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/out_2']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/out_2']],...
		'Port','2',...
		'position',[355,80,375,100])

add_block('built-in/Mux',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/Mux']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/Mux']],...
		'inputs','[in_size 1 1]',...
		'position',[110,59,140,101])

add_block('built-in/Demux',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/Demux']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/Demux']],...
		'outputs','[out_size 1]',...
		'position',[290,62,330,98])

add_block('built-in/S-Function',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/S-function']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/S-function']],...
		'function name','regdown',...
		'parameters','ini_idx, idx_inc, thrshld, cycl_flag',...
		'position',[185,70,235,90])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_1']],...
		'position',[15,55,35,75])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_2']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_2']],...
		'Port','2',...
		'position',[40,70,60,90])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_3']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe/in_3']],...
		'Port','3',...
		'position',[65,85,85,105])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[240,80;285,80])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[145,80;180,80])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[40,65;105,65])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[335,70;385,70])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[65,80;105,80])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[335,90;350,90])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],[90,95;105,95])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w,u,z);Buffer dwn',...
		'Mask Type','Triggered buffer down')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'Mask Dialogue','Rising edge of the 2nd port triggers 1st port vector signal in. Rising edge of the 3rd port triggers 1st outport signal out.|Input signal vector size:|Initial index (integer vector):|Increment for each index (integer vector):|Trigger threshold:|When index exceed register size, 1: cyclic out, 0: zero out:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'Mask Translate','in_size=@1;ini_idx=@2;idx_inc=@3;thrshld=@4;cycl_flag=@5;out_size=length(ini_idx);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);[x,y]=trigicon(1,75,get_param(gcb,''orientation''),2);[u,z]=trigicon(0,50,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'Mask Help','The block refreshes its registers with the vector input from the 1st inport at the rising edge of the 2nd inport pulse. The 1st outport outputs the elements of the registers starting with the given initial index. The rising edge of the 3rd inport pulse triggers the 1st output to output the register value with the index increasing the increment value. The second outport outputs a spike pulse when the internal register is refreshed.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'Mask Entries','2\/[1 0]\/[0 0]\/1\/0\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Haltestufe']],...
		'position',[260,138,340,182])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],'Location',[19,610,374,740])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/in_2']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/in_2']],...
		'Port','2',...
		'position',[30,70,50,90])

add_block('built-in/Inport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/in_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/in_1']],...
		'position',[30,55,50,75])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/out_2']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/out_2']],...
		'Port','2',...
		'position',[330,70,350,90])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/out_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/out_1']],...
		'position',[330,55,350,75])

add_block('built-in/Mux',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/Mux']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/Mux']],...
		'inputs','2',...
		'position',[80,56,115,89])

add_block('built-in/S-Function',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/S-function']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/S-function']],...
		'function name','regshift',...
		'parameters','shft_out, thrhld',...
		'position',[150,65,200,85])

add_block('built-in/Demux',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/Demux']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister/Demux']],...
		'outputs','[len_rg, 1]',...
		'position',[260,55,300,90])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[55,80;75,80])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[55,65;75,65])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[305,80;325,80])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[305,65;325,65])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[205,75;255,75])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],[120,75;145,75])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);Reg. shift',...
		'Mask Type','Register-shift')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'Mask Dialogue','The rising edge of the 2nd port pulse\ntriggers the block to input the 1st port data and to shift the register.|Delay steps (output length is same as this vector size):|Threshold in detecting the rising edge of the pulse:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'Mask Translate','shft_out=@1;thrhld=@2;len_rg=length(@1);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);[x,y]=trigicon(1,75,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'Mask Help','This block stores the scalar input signal from the 1st input port at the rising edge of the pulse from the 2nd port. The 1st outport outputs a vector with its size the same as the "Delay steps" entree of this block. The maximum delay is the register size of this block. The second outport outputs a positive pulse when the register is\nrefreshed.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'Mask Entries','[2 1]\/1\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Schieberegister']],...
		'position',[120,133,200,177])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],'Location',[158,441,759,682])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/out_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])

add_block('built-in/Gain',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Gain']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Product',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Product']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Logical Operator',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Logical',13,'Operator1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Logical Operator',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Logical',13,'Operator']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Constant',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Constant1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Clock',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Clock1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Relational Operator',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Relational',13,'operator']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Sum',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Sum1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Sum',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Sum']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Constant',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Constant']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Unit Delay',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Unit Delay']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Unit Delay',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Unit Delay1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[390,50;430,50;430,110;450,110])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[320,50;350,50])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[540,115;555,115])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[485,115;505,115])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[405,120;450,120])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[320,110;365,110])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[50,40;130,40])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[160,45;280,45])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],[155,130;245,130;245,55;280,55])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'Mask Entries','.5\/.25\/1\/0\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Taktgeber']],...
		'position',[35,147,70,183])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],'Location',[355,528,737,675])

add_block('built-in/S-Function',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'BackGround',5,...
		'function name','trigwksp',...
		'parameters','var,thd,cyclFlag,ini',...
		'Mask Display','Triggered\nread')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'Mask Type','Read from workspace')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'Mask Dialogue','The raising edge of input pulse trigger the block output the next row from the workspace variable.|Read the variable:|Threshold for the input pulse:|Cyclic read variable (1) or amend zeros (0).|Output before first trigger:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'Mask Translate','var=@1;thd=@2;cyclFlag=@3;ini=@4;')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'Mask Help','This block reads the data from a workspace variable. The output is refreshed at the raising edge of the input pulse.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Message source']],...
		'Mask Entries','var\/.1\/cyc\/ini\/',...
		'position',[180,53,255,97])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/out_1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/out_1']],...
		'position',[295,65,315,85])


%     Subsystem  ['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])

add_block('built-in/S-Function',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','ts\/1\/off\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'position',[50,56,110,94])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],[115,75;175,75])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],[260,75;290,75])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'Mask Display','plot(0,0,100,100,x,y);Rd wksp',...
		'Mask Type','Read from workspace')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'Mask Dialogue','Read from a workspace variable at\nsampling time point.|Variable (column_number=block_output_length):|Data output sample time (sec):|Repeat flag (1: repeat read, 0: output zeros after eof).|Initial output:')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'Mask Translate','var=@1;td=@2;ts=td(1);if (length(td)>=2),off=td(2);else off=0;end;cyc=@3;ini=@4;[x,y]=srcsicon(7);')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'Mask Help','This block reads from a workspace variable at a given sample time. The column number is the block output vector length. When the simulation reaches the end of the variable (eof), the block will cyclically output from the first row of the variable or output zeros based on the repeat flag entree.')
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'Mask Entries','randint(2000,1,2)\/.5\/1\/1\/')


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Bitstrom']],...
		'position',[25,48,85,92])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Symbol']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Symbol']],...
		'Port','2',...
		'position',[480,140,500,160])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Binär']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Binär']],...
		'position',[480,60,500,80])

add_block('built-in/Outport',[sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Takt']])
set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK/Takt']],...
		'Port','3',...
		'position',[480,195,500,215])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[90,70;255,70])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[105,70;115,145])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[205,165;225,165;225,160;255,160])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[225,165;225,175;255,175])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[75,165;115,165])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[345,150;365,150])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[205,145;255,145])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[345,70;475,70])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[455,150;475,150])
add_line([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],[345,170;355,170;355,205;475,205])


%     Finished composite block ['Quaternäre',13,'Quelle',13,'für 4-ASK'].

set_param([sys,'/',['Quaternäre',13,'Quelle',13,'für 4-ASK']],...
		'position',[40,99,70,151])


%     Subsystem  ['Diagramme',13,'sendeseitig'].

new_system([sys,'/',['Diagramme',13,'sendeseitig']])
set_param([sys,'/',['Diagramme',13,'sendeseitig']],'Location',[475,310,844,551])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'sendeseitig/Constant1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Constant1']],...
		'Value','0',...
		'position',[130,130,150,150])

add_block('built-in/Step Fcn',[sys,'/',['Diagramme',13,'sendeseitig/Step input']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Step input']],...
		'Time','starttime',...
		'position',[35,85,55,105])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/in_1']],...
		'position',[35,40,55,60])

add_block('built-in/Switch',[sys,'/',['Diagramme',13,'sendeseitig/Switch']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Switch']],...
		'Threshold','1',...
		'position',[110,44,135,76])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'sendeseitig/Constant']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Constant']],...
		'Value','Inf',...
		'position',[35,130,55,150])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Mux1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Mux1']],...
		'inputs','2',...
		'position',[185,96,220,129])


%     Subsystem  ['Diagramme',13,'sendeseitig/Augendiagramm'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/in_1']],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Augendiagramm'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'position',[275,37,330,73])


%     Subsystem  ['Diagramme',13,'sendeseitig/Trajektorie'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_1']],...
		'position',[15,55,35,75])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_2']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_2']],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Mux']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Mux']],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Plot1']],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[40,65;45,65;45,80;60,80])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[45,125;50,125;60,95])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[105,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Trajektorie'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'position',[275,105,330,140])


%     Subsystem  ['Diagramme',13,'sendeseitig/Signalraumpunkte'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/in_1']],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Signalraumpunkte'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'position',[275,173,330,207])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Mux']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Mux']],...
		'inputs','2',...
		'position',[185,36,220,69])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[140,60;180,60])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[150,60;150,105;180,105])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[155,140;165,140;165,45;180,45])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[165,120;180,120])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[225,115;270,115])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[250,115;250,190;270,190])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,140;95,140;105,70])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,95;75,95;75,60;105,60])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,50;105,50])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[225,55;270,55])
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','Diagramme')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','0\/40\/0\/')


%     Finished composite block ['Diagramme',13,'sendeseitig'].

set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'position',[310,10,365,50])


%     Subsystem  ['Diagramme',13,'empfangsseitig'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],'Location',[475,310,844,551])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Mux']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Mux']],...
		'inputs','2',...
		'position',[185,36,220,69])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Signalraumpunkte'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/in_1']],...
		'position',[75,80,95,100])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Signalraumpunkte'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'position',[275,173,330,207])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Trajektorie'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Plot1']],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Mux']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Mux']],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_2']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_2']],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_1']],...
		'position',[15,55,35,75])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[105,90;125,90])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[45,125;50,125;60,95])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[40,65;45,65;45,80;60,80])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Trajektorie'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'position',[275,105,330,140])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Augendiagramm'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/in_1']],...
		'position',[75,80,95,100])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Augendiagramm'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'position',[275,37,330,73])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Mux1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Mux1']],...
		'inputs','2',...
		'position',[185,96,220,129])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'empfangsseitig/Constant']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Constant']],...
		'Value','Inf',...
		'position',[35,130,55,150])

add_block('built-in/Switch',[sys,'/',['Diagramme',13,'empfangsseitig/Switch']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Switch']],...
		'Threshold','1',...
		'position',[110,44,135,76])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/in_1']],...
		'position',[35,40,55,60])

add_block('built-in/Step Fcn',[sys,'/',['Diagramme',13,'empfangsseitig/Step input']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Step input']],...
		'Time','starttime',...
		'position',[35,85,55,105])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'empfangsseitig/Constant1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Constant1']],...
		'Value','0',...
		'position',[130,130,150,150])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[225,55;270,55])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,50;105,50])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,95;75,95;75,60;105,60])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,140;95,140;105,70])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[225,115;270,115])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[250,115;250,190;270,190])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[155,140;165,140;165,45;180,45])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[165,120;180,120])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[140,60;180,60])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[150,60;150,105;180,105])
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','Diagramme')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','1\/40\/.075\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'position',[865,10,920,50])


%     Subsystem  'Doppelklick2'.

new_system([sys,'/','Doppelklick2'])
set_param([sys,'/','Doppelklick2'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick2'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Doppelklick2'.

set_param([sys,'/','Doppelklick2'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[455,80,590,106])
add_line(sys,[270,175;280,175])
add_line(sys,[205,125;375,125])
add_line(sys,[410,135;475,135])
add_line(sys,[955,130;990,130])
add_line(sys,[360,175;360,140;375,140])
add_line(sys,[75,125;115,125])
add_line(sys,[520,30;530,30])
add_line(sys,[690,130;725,130])
add_line(sys,[435,135;435,220])
add_line(sys,[225,125;225,220])
add_line(sys,[285,125;285,30;305,30])
add_line(sys,[795,130;865,130])
add_line(sys,[840,130;840,30;860,30])
add_line(sys,[840,130;840,180])
add_line(sys,[565,135;655,135])
add_line(sys,[590,135;590,220])
add_line(sys,[635,30;640,30;640,120;655,120])
add_line(sys,[95,125;95,265;895,265;895,210;930,220])
add_line(sys,[970,130;970,220])
add_line(sys,[95,240;115,240])
add_line(sys,[75,110;110,110;110,35;170,35])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
