function [ret,x0,str,ts,xts]=bpswnymf(t,x,u,flag);
%BPSWNYMF	is the M-file description of the SIMULINK system named BPSWNYMF.
%	The block-diagram can be displayed by typing: BPSWNYMF.
%
%	SYS=BPSWNYMF(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes BPSWNYMF to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling BPSWNYMF with a FLAG of zero:
%	[SIZES]=BPSWNYMF([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = mfilename;
new_system(sys)
simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[194,42,1259,319])
     open_system(sys)
end;
set_param(sys,'algorithm',     'RK-45')
set_param(sys,'Start time',    '0.0')
set_param(sys,'Stop time',     '999999')
set_param(sys,'Min step size', '0.000001')
set_param(sys,'Max step size', '10')
set_param(sys,'Relative error','1e-6')
set_param(sys,'Return vars',   '')

add_block('built-in/Scope',[sys,'/','x(t)'])
set_param([sys,'/','x(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[344,436,1279,536])
open_system([sys,'/','x(t)'])
set_param([sys,'/','x(t)'],...
		'position',[210,205,240,235])

add_block('built-in/Scope',[sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'move name',0,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[344,338,1279,438])
open_system([sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'position',[85,205,115,235])


%     Subsystem  'Error rate'.

new_system([sys,'/','Error rate'])
set_param([sys,'/','Error rate'],'Location',[255,368,509,510])

add_block('built-in/Inport',[sys,'/','Error rate/in_2'])
set_param([sys,'/','Error rate/in_2'],...
		'Port','2',...
		'position',[15,60,35,80])

add_block('built-in/Inport',[sys,'/','Error rate/in_1'])
set_param([sys,'/','Error rate/in_1'],...
		'position',[15,45,35,65])

add_block('built-in/Mux',[sys,'/','Error rate/Mux'])
set_param([sys,'/','Error rate/Mux'],...
		'inputs','2',...
		'position',[65,46,100,79])

add_block('built-in/S-Function',[sys,'/','Error rate/S-function'])
set_param([sys,'/','Error rate/S-function'],...
		'function name','sbiterr',...
		'parameters','num_lin, K, TDelay, Sample',...
		'position',[130,52,195,78])
add_line([sys,'/','Error rate'],[40,70;60,70])
add_line([sys,'/','Error rate'],[40,55;60,55])
add_line([sys,'/','Error rate'],[105,65;125,65])
set_param([sys,'/','Error rate'],...
		'Mask Display','Error\nmeter',...
		'Mask Type','Symbol/bit error counter')
set_param([sys,'/','Error rate'],...
		'Mask Dialogue','Use the input data from the 1st port as the reference signal to detect the number of errors and error rate of the 2nd signal.|Bit per symbol:|Number of digits on display:|Delay between 1st port and 2nd port:|Sample time (sec):')
set_param([sys,'/','Error rate'],...
		'Mask Translate','K=@1;num_lin=@2;TDelay=@3;Sample=@4;')
set_param([sys,'/','Error rate'],...
		'Mask Help','The signal from the first port must be a scalar. The second input port can be a vector with a delay to the first port signal. The comparison happens only at the sampling point.')
set_param([sys,'/','Error rate'],...
		'Mask Entries','1\/10\/12\/1\/')


%     Finished composite block 'Error rate'.

set_param([sys,'/','Error rate'],...
		'orientation',1,...
		'position',[890,230,970,270])


%     Subsystem  ['Schwellenwert-',13,'Entscheider'].

new_system([sys,'/',['Schwellenwert-',13,'Entscheider']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider']],'Location',[159,417,467,586])

add_block('built-in/Constant',[sys,'/',['Schwellenwert-',13,'Entscheider/Constant']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/Constant']],...
		'Value','0',...
		'position',[65,105,85,125])

add_block('built-in/Relational Operator',[sys,'/',['Schwellenwert-',13,'Entscheider/Relational',13,'Operator1']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/Relational',13,'Operator1']],...
		'Operator','<',...
		'position',[140,92,170,123])

add_block('built-in/Sum',[sys,'/',['Schwellenwert-',13,'Entscheider/Sum']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/Sum']],...
		'inputs','+-',...
		'position',[215,64,235,91])

add_block('built-in/Relational Operator',[sys,'/',['Schwellenwert-',13,'Entscheider/Relational',13,'Operator']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/Relational',13,'Operator']],...
		'Operator','>',...
		'position',[140,32,170,63])

add_block('built-in/Inport',[sys,'/',['Schwellenwert-',13,'Entscheider/in_1']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/in_1']],...
		'position',[35,30,55,50])

add_block('built-in/Outport',[sys,'/',['Schwellenwert-',13,'Entscheider/out_1']])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider/out_1']],...
		'position',[265,70,285,90])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[240,80;260,80])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[175,50;185,50;185,70;210,70])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[175,110;185,110;185,85;210,85])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[90,115;135,115])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[110,115;110,55;135,55])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[60,40;135,40])
add_line([sys,'/',['Schwellenwert-',13,'Entscheider']],[95,40;95,100;135,100])
set_param([sys,'/',['Schwellenwert-',13,'Entscheider']],...
		'Mask Display','plot(-50,-50,50,50,[-50,50],[0,0],[0,0],[-50,50],[-40,0],[-30,-30],[0,40],[30,30])',...
		'Mask Type','Sign',...
		'Mask Dialogue','y = sign(x)')
set_param([sys,'/',['Schwellenwert-',13,'Entscheider']],...
		'Mask Help','Sign Function:\n\t\t\ty = 1 if x > 0\n\t\t\ty = 0 if x = 0\n\t\t\ty = -1 if x < 0')


%     Finished composite block ['Schwellenwert-',13,'Entscheider'].

set_param([sys,'/',['Schwellenwert-',13,'Entscheider']],...
		'position',[890,112,920,138])

add_block('built-in/Scope',[sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[341,824,1277,924])
open_system([sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'position',[830,180,860,210])

add_block('built-in/Product',[sys,'/','Product1'])
set_param([sys,'/','Product1'],...
		'hide name',0,...
		'position',[640,113,670,137])

add_block('built-in/Scope',[sys,'/','Senkensignal v(t)'])
set_param([sys,'/','Senkensignal v(t)'],...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[341,922,1277,1022])
open_system([sys,'/','Senkensignal v(t)'])
set_param([sys,'/','Senkensignal v(t)'],...
		'position',[990,110,1020,140])

add_block('built-in/Scope',[sys,'/','Empfangssignal r(t)'])
set_param([sys,'/','Empfangssignal r(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[342,629,1278,729])
open_system([sys,'/','Empfangssignal r(t)'])
set_param([sys,'/','Empfangssignal r(t)'],...
		'position',[585,215,615,245])


%     Subsystem  'Kanal'.

new_system([sys,'/','Kanal'])
set_param([sys,'/','Kanal'],'Location',[11,262,273,408])

add_block('built-in/Inport',[sys,'/','Kanal/in_1'])
set_param([sys,'/','Kanal/in_1'],...
		'position',[45,10,65,30])

add_block('built-in/Outport',[sys,'/','Kanal/out_1'])
set_param([sys,'/','Kanal/out_1'],...
		'position',[200,55,220,75])

add_block('built-in/Sum',[sys,'/','Kanal/Sum'])
set_param([sys,'/','Kanal/Sum'],...
		'position',[150,55,170,75])


%     Subsystem  ['Kanal/Gaussian noise',13,'generator'].

new_system([sys,'/',['Kanal/Gaussian noise',13,'generator']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],'Location',[22,119,370,243])

add_block('built-in/State-Space',[sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'Mask Display','K',...
		'Mask Type','Matrix Gain',...
		'Mask Dialogue','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'Mask Translate','K = @1;',...
		'Mask Help','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'Mask Entries','d\/')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'position',[140,61,165,89])

add_block('built-in/White Noise',[sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']],...
		'Seed','s',...
		'position',[35,57,80,93])

add_block('built-in/Constant',[sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']],...
		'Value','m',...
		'position',[140,20,160,40])

add_block('built-in/Sum',[sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']],...
		'position',[220,60,240,80])

add_block('built-in/Outport',[sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']],...
		'position',[285,60,305,80])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[165,30;190,30;190,65;215,65])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[245,70;280,70])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[170,75;215,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[85,75;135,75])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Display','plot(0,0,100,100,x,y);Gaussian',...
		'Mask Type','Gaussian noise generator')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Dialogue','Generate Gaussian distributed noise with\ngiven mean and variance value.|Mean value:|Variance (vector or matrix):|Initial seed:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=srcsicon(3);')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Help','When the mean value and seed are vectors, the output of this block is a vector. The length of the vector is the same as the length of the mean value vector or the length of the seed. When the variance entry is a vector, the variance is a diagonal matrix.')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Entries','m\/d\/s\/')


%     Finished composite block ['Kanal/Gaussian noise',13,'generator'].

set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'position',[25,48,105,92])
add_line([sys,'/','Kanal'],[175,65;195,65])
add_line([sys,'/','Kanal'],[70,20;115,20;115,60;145,60])
add_line([sys,'/','Kanal'],[110,70;145,70])
set_param([sys,'/','Kanal'],...
		'Mask Display','plot(0,0,100,100,x,y);AWGN',...
		'Mask Type','AWGN channel, fixed parameter')
set_param([sys,'/','Kanal'],...
		'Mask Dialogue','Additive white Gaussian noise channel\nwith fixed mean and variance.|Mean value:|Variance (std^2):|Initial Seed:',...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=chanicon;')
set_param([sys,'/','Kanal'],...
		'Mask Help','This block adds white Gaussian noise to the input signal. The mean and the variance can be a scalar or vector with the same length as the input signal.',...
		'Mask Entries','0\/.0001\/12345\/')


%     Finished composite block 'Kanal'.

set_param([sys,'/','Kanal'],...
		'position',[505,108,585,152])

add_block('built-in/Scope',[sys,'/','Sendesignal s(t)'])
set_param([sys,'/','Sendesignal s(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[343,533,1279,633])
open_system([sys,'/','Sendesignal s(t)'])
set_param([sys,'/','Sendesignal s(t)'],...
		'position',[445,180,475,210])

add_block('built-in/Product',[sys,'/','Product'])
set_param([sys,'/','Product'],...
		'hide name',0,...
		'position',[400,118,430,142])

add_block('built-in/Fcn',[sys,'/','Fcn1'])
set_param([sys,'/','Fcn1'],...
		'hide name',0,...
		'Expr','cos(4*pi*u)',...
		'position',[275,145,370,175])

add_block('built-in/Clock',[sys,'/','Clock'])
set_param([sys,'/','Clock'],...
		'hide name',0,...
		'position',[235,150,255,170])


%     Subsystem  'Quelle'.

new_system([sys,'/','Quelle'])
set_param([sys,'/','Quelle'],'Location',[4,149,283,322])

add_block('built-in/Fcn',[sys,'/','Quelle/Fcn'])
set_param([sys,'/','Quelle/Fcn'],...
		'Expr','1-2*u',...
		'position',[160,75,200,95])

add_block('built-in/Outport',[sys,'/','Quelle/out_1'])
set_param([sys,'/','Quelle/out_1'],...
		'position',[230,75,250,95])


%     Subsystem  'Quelle/Quelle'.

new_system([sys,'/','Quelle/Quelle'])
set_param([sys,'/','Quelle/Quelle'],'Location',[355,528,737,675])


%     Subsystem  ['Quelle/Quelle/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/S-Function',[sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])

add_block('built-in/Outport',[sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])
add_line([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','ts\/1\/off\/')


%     Finished composite block ['Quelle/Quelle/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'position',[50,56,110,94])

add_block('built-in/Outport',[sys,'/','Quelle/Quelle/out_1'])
set_param([sys,'/','Quelle/Quelle/out_1'],...
		'position',[295,65,315,85])

add_block('built-in/S-Function',[sys,'/','Quelle/Quelle/Message source'])
set_param([sys,'/','Quelle/Quelle/Message source'],...
		'BackGround',5,...
		'function name','trigwksp',...
		'parameters','var,thd,cyclFlag,ini',...
		'Mask Display','Triggered\nread',...
		'Mask Type','Read from workspace')
set_param([sys,'/','Quelle/Quelle/Message source'],...
		'Mask Dialogue','The raising edge of input pulse trigger the block output the next row from the workspace variable.|Read the variable:|Threshold for the input pulse:|Cyclic read variable (1) or amend zeros (0).|Output before first trigger:')
set_param([sys,'/','Quelle/Quelle/Message source'],...
		'Mask Translate','var=@1;thd=@2;cyclFlag=@3;ini=@4;',...
		'Mask Help','This block reads the data from a workspace variable. The output is refreshed at the raising edge of the input pulse.')
set_param([sys,'/','Quelle/Quelle/Message source'],...
		'Mask Entries','var\/.1\/cyc\/ini\/',...
		'position',[180,53,255,97])
add_line([sys,'/','Quelle/Quelle'],[260,75;290,75])
add_line([sys,'/','Quelle/Quelle'],[115,75;175,75])
set_param([sys,'/','Quelle/Quelle'],...
		'Mask Display','plot(0,0,100,100,x,y);Rd wksp',...
		'Mask Type','Read from workspace')
set_param([sys,'/','Quelle/Quelle'],...
		'Mask Dialogue','Read from a workspace variable at\nsampling time point.|Variable (column_number=block_output_length):|Data output sample time (sec):|Repeat flag (1: repeat read, 0: output zeros after eof).|Initial output:')
set_param([sys,'/','Quelle/Quelle'],...
		'Mask Translate','var=@1;td=@2;ts=td(1);if (length(td)>=2),off=td(2);else off=0;end;cyc=@3;ini=@4;[x,y]=srcsicon(7);')
set_param([sys,'/','Quelle/Quelle'],...
		'Mask Help','This block reads from a workspace variable at a given sample time. The column number is the block output vector length. When the simulation reaches the end of the variable (eof), the block will cyclically output from the first row of the variable or output zeros based on the repeat flag entree.')
set_param([sys,'/','Quelle/Quelle'],...
		'Mask Entries','randint(1000,1,2)\/1\/1\/1\/')


%     Finished composite block 'Quelle/Quelle'.

set_param([sys,'/','Quelle/Quelle'],...
		'position',[70,63,135,107])
add_line([sys,'/','Quelle'],[140,85;155,85])
add_line([sys,'/','Quelle'],[205,85;225,85])


%     Finished composite block 'Quelle'.

set_param([sys,'/','Quelle'],...
		'position',[10,98,40,152])


%     Subsystem  'Wurzel-Nyquist'.

new_system([sys,'/','Wurzel-Nyquist'])
set_param([sys,'/','Wurzel-Nyquist'],'Location',[131,545,589,761])


%     Subsystem  ['Wurzel-Nyquist/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/S-Function',[sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])
add_line([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','td\/1\/off\/')


%     Finished composite block ['Wurzel-Nyquist/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Wurzel-Nyquist/Pulses deivide',13,'same sample time1']],...
		'position',[35,71,95,109])

add_block('built-in/Inport',[sys,'/','Wurzel-Nyquist/in_1'])
set_param([sys,'/','Wurzel-Nyquist/in_1'],...
		'position',[35,30,55,50])

add_block('built-in/Outport',[sys,'/','Wurzel-Nyquist/out_1'])
set_param([sys,'/','Wurzel-Nyquist/out_1'],...
		'position',[330,40,350,60])

add_block('built-in/Filter',[sys,'/','Wurzel-Nyquist/Filter'])
set_param([sys,'/','Wurzel-Nyquist/Filter'],...
		'Numerator','num',...
		'Denominator','den',...
		'Sample time','ts',...
		'position',[255,31,310,69])


%     Subsystem  'Wurzel-Nyquist/Memory Impulse'.

new_system([sys,'/','Wurzel-Nyquist/Memory Impulse'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse'],'Location',[541,520,939,745])

add_block('built-in/Inport',[sys,'/','Wurzel-Nyquist/Memory Impulse/in_2'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/in_2'],...
		'Port','2',...
		'position',[25,30,45,50])


%     Subsystem  ['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector'].

new_system([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],'Location',[419,521,808,713])

add_block('built-in/Unit Delay',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Unit Delay']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Unit Delay']],...
		'Sample time','ts',...
		'position',[120,87,170,103])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/out_1']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/out_1']],...
		'position',[340,25,360,45])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator1']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator1']],...
		'position',[200,88,230,112])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator2']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator2']],...
		'Operator','>',...
		'position',[265,23,295,47])

add_block('built-in/Constant',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/one1']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/one1']],...
		'Value','thld',...
		'position',[30,135,60,155])

add_block('built-in/Inport',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/in_1']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/in_1']],...
		'position',[10,15,30,35])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator']],...
		'position',[135,18,165,42])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[35,25;130,25])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[45,25;45,95;115,95])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[175,95;195,95])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[65,145;100,145;100,35;130,35])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[100,145;180,145;180,105;195,105])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[170,30;260,30])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[235,100;240,100;240,40;260,40])
add_line([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[300,35;335,35])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Display','Edge\nDetector',...
		'Mask Type','Edge Detection',...
		'Mask Dialogue','Rising edge detection:|Threshold:|Sampling time:')
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Translate','thld=@1;ts=@2;')
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Help','When the input signal rising edge passed the given shreshold, this block outputs one, otherwise outputs zero.')
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Entries','thr\/ts\/')


%     Finished composite block ['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector'].

set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'position',[65,26,120,54])

add_block('built-in/Switch',[sys,'/','Wurzel-Nyquist/Memory Impulse/Switch'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/Switch'],...
		'Threshold','.5',...
		'position',[295,124,320,156])

add_block('built-in/Constant',[sys,'/','Wurzel-Nyquist/Memory Impulse/Constant'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/Constant'],...
		'Value','x',...
		'position',[210,155,230,175])

add_block('built-in/Outport',[sys,'/','Wurzel-Nyquist/Memory Impulse/out_1'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/out_1'],...
		'position',[355,130,375,150])

add_block('built-in/Product',[sys,'/','Wurzel-Nyquist/Memory Impulse/Product'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/Product'],...
		'position',[155,90,180,110])

add_block('built-in/Zero-Order Hold',[sys,'/',['Wurzel-Nyquist/Memory Impulse/Zero-Order',13,'Hold']])
set_param([sys,'/',['Wurzel-Nyquist/Memory Impulse/Zero-Order',13,'Hold']],...
		'Sample time','ts',...
		'position',[205,84,240,116])

add_block('built-in/Inport',[sys,'/','Wurzel-Nyquist/Memory Impulse/in_1'])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse/in_1'],...
		'position',[35,185,55,205])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[50,40;60,40])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[125,40;130,40;130,95;150,95])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[235,165;250,165;250,140;290,140])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[325,140;350,140])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[60,195;280,195;290,150])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[95,195;95,105;150,105])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[185,100;200,100])
add_line([sys,'/','Wurzel-Nyquist/Memory Impulse'],[245,100;260,100;260,130;290,130])
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse'],...
		'Mask Display','1/sinc',...
		'Mask Type','Impulse',...
		'Mask Dialogue','1/sinc filter:|Holding time:|Threshold for clock pulse: ',...
		'Mask Translate','ts=@1;thr=@2;x=thr>0;')
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse'],...
		'Mask Help','When the threshold is greater than zero, this block outputs an impulse signal, which begins at the raising edge of the second input and lasts the holding time. The impulse holds a constant amplitude, which equals the amplitude of the first input at the begining of the impulse. A clock raising edge will trigger next impulse. When the threshold is less or equal to zero, this block faithfully outputs the first input.')
set_param([sys,'/','Wurzel-Nyquist/Memory Impulse'],...
		'Mask Entries','ts\/x\/')


%     Finished composite block 'Wurzel-Nyquist/Memory Impulse'.

set_param([sys,'/','Wurzel-Nyquist/Memory Impulse'],...
		'position',[155,30,225,70])
add_line([sys,'/','Wurzel-Nyquist'],[315,50;325,50])
add_line([sys,'/','Wurzel-Nyquist'],[60,40;150,40])
add_line([sys,'/','Wurzel-Nyquist'],[230,50;250,50])
add_line([sys,'/','Wurzel-Nyquist'],[100,90;115,90;115,60;150,60])
set_param([sys,'/','Wurzel-Nyquist'],...
		'Mask Display','R-C\nfilter',...
		'Mask Type','R-C filter')
set_param([sys,'/','Wurzel-Nyquist'],...
		'Mask Dialogue','Design a raised cosine filter and use it to filter the input signal.|Symbol interval (sec):|Computation sampling time (sec):|Filter rolloff factor:|Delay step (integer to multiply symbol interval):|Filter type (FIR or IIR) / (Normal or Sqrt):|With or without sinc filter (1 or 0, suggest 1):')
set_param([sys,'/','Wurzel-Nyquist'],...
		'Mask Translate','td=@1;if length(td)>1,off=td(2);td=td(1);else,off=0;end;ts=@2;R=@3;delay=@4;fil=@5;[num,den]=rcosine(1/td(1),1/ts(1),fil,R,delay);x=@6/2;')
set_param([sys,'/','Wurzel-Nyquist'],...
		'Mask Help','This block designs a raised cosine filter using the specified parameter. The filter is used to filter the input signal. You can optionally use the sinc filter in the filtering computation.')
set_param([sys,'/','Wurzel-Nyquist'],...
		'Mask Entries','1\/.05\/.5\/6\/''FIR/Sqrt''\/1\/')


%     Finished composite block 'Wurzel-Nyquist'.

set_param([sys,'/','Wurzel-Nyquist'],...
		'position',[85,103,165,147])


%     Subsystem  'Signalraumkonstellation_'.

new_system([sys,'/','Signalraumkonstellation_'])
set_param([sys,'/','Signalraumkonstellation_'],'Location',[0,38,1264,980])
set_param([sys,'/','Signalraumkonstellation_'],...
		'Mask Display','Signalraum\nKonstellation',...
		'Mask Dialogue','eval(''figure''); eval(''modmap(''''psk'''',2)'')')


%     Finished composite block 'Signalraumkonstellation_'.

set_param([sys,'/','Signalraumkonstellation_'],...
		'BackGround',7,...
		'hide name',0,...
		'position',[30,19,115,56])

add_block('built-in/Scope',[sys,'/','x_e(t)'])
set_param([sys,'/','x_e(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[342,727,1278,827])
open_system([sys,'/','x_e(t)'])
set_param([sys,'/','x_e(t)'],...
		'position',[675,180,705,210])

add_block('built-in/Gain',[sys,'/','Gain'])
set_param([sys,'/','Gain'],...
		'Gain','4',...
		'position',[185,112,210,138])


%     Subsystem  ['Wurzel-Nyquist',13,'Filter'].

new_system([sys,'/',['Wurzel-Nyquist',13,'Filter']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],'Location',[131,545,589,761])


%     Subsystem  ['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/S-Function',[sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','td\/1\/off\/')


%     Finished composite block ['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Pulses deivide',13,'same sample time1']],...
		'position',[35,71,95,109])

add_block('built-in/Inport',[sys,'/',['Wurzel-Nyquist',13,'Filter/in_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/in_1']],...
		'position',[35,30,55,50])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist',13,'Filter/out_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/out_1']],...
		'position',[330,40,350,60])

add_block('built-in/Filter',[sys,'/',['Wurzel-Nyquist',13,'Filter/Filter']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Filter']],...
		'Numerator','num',...
		'Denominator','den',...
		'Sample time','ts',...
		'position',[255,31,310,69])


%     Subsystem  ['Wurzel-Nyquist',13,'Filter/Memory Impulse'].

new_system([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],'Location',[541,520,939,745])

add_block('built-in/Inport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/in_2']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/in_2']],...
		'Port','2',...
		'position',[25,30,45,50])


%     Subsystem  ['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector'].

new_system([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],'Location',[419,521,808,713])

add_block('built-in/Unit Delay',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Unit Delay']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Unit Delay']],...
		'Sample time','ts',...
		'position',[120,87,170,103])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/out_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/out_1']],...
		'position',[340,25,360,45])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator1']],...
		'position',[200,88,230,112])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator2']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator2']],...
		'Operator','>',...
		'position',[265,23,295,47])

add_block('built-in/Constant',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/one1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/one1']],...
		'Value','thld',...
		'position',[30,135,60,155])

add_block('built-in/Inport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/in_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/in_1']],...
		'position',[10,15,30,35])

add_block('built-in/Relational Operator',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector/Relational',13,'Operator']],...
		'position',[135,18,165,42])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[35,25;130,25])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[45,25;45,95;115,95])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[175,95;195,95])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[65,145;100,145;100,35;130,35])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[100,145;180,145;180,105;195,105])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[170,30;260,30])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[235,100;240,100;240,40;260,40])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],[300,35;335,35])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Display','Edge\nDetector',...
		'Mask Type','Edge Detection')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Dialogue','Rising edge detection:|Threshold:|Sampling time:',...
		'Mask Translate','thld=@1;ts=@2;')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Help','When the input signal rising edge passed the given shreshold, this block outputs one, otherwise outputs zero.')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'Mask Entries','thr\/ts\/')


%     Finished composite block ['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector'].

set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/discrete',13,'Rising edge',13,'detector']],...
		'position',[65,26,120,54])

add_block('built-in/Switch',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Switch']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Switch']],...
		'Threshold','.5',...
		'position',[295,124,320,156])

add_block('built-in/Constant',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Constant']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Constant']],...
		'Value','x',...
		'position',[210,155,230,175])

add_block('built-in/Outport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/out_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/out_1']],...
		'position',[355,130,375,150])

add_block('built-in/Product',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Product']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Product']],...
		'position',[155,90,180,110])

add_block('built-in/Zero-Order Hold',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Zero-Order',13,'Hold']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/Zero-Order',13,'Hold']],...
		'Sample time','ts',...
		'position',[205,84,240,116])

add_block('built-in/Inport',[sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/in_1']])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse/in_1']],...
		'position',[35,185,55,205])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[50,40;60,40])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[125,40;130,40;130,95;150,95])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[235,165;250,165;250,140;290,140])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[325,140;350,140])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[60,195;280,195;290,150])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[95,195;95,105;150,105])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[185,100;200,100])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],[245,100;260,100;260,130;290,130])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],...
		'Mask Display','1/sinc',...
		'Mask Type','Impulse',...
		'Mask Dialogue','1/sinc filter:|Holding time:|Threshold for clock pulse: ')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],...
		'Mask Translate','ts=@1;thr=@2;x=thr>0;')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],...
		'Mask Help','When the threshold is greater than zero, this block outputs an impulse signal, which begins at the raising edge of the second input and lasts the holding time. The impulse holds a constant amplitude, which equals the amplitude of the first input at the begining of the impulse. A clock raising edge will trigger next impulse. When the threshold is less or equal to zero, this block faithfully outputs the first input.')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],...
		'Mask Entries','ts\/x\/')


%     Finished composite block ['Wurzel-Nyquist',13,'Filter/Memory Impulse'].

set_param([sys,'/',['Wurzel-Nyquist',13,'Filter/Memory Impulse']],...
		'position',[155,30,225,70])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter']],[315,50;325,50])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter']],[60,40;150,40])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter']],[230,50;250,50])
add_line([sys,'/',['Wurzel-Nyquist',13,'Filter']],[100,90;115,90;115,60;150,60])
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'Mask Display','R-C\nfilter',...
		'Mask Type','R-C filter')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'Mask Dialogue','Design a raised cosine filter and use it to filter the input signal.|Symbol interval (sec):|Computation sampling time (sec):|Filter rolloff factor:|Delay step (integer to multiply symbol interval):|Filter type (FIR or IIR) / (Normal or Sqrt):|With or without sinc filter (1 or 0, suggest 1):')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'Mask Translate','td=@1;if length(td)>1,off=td(2);td=td(1);else,off=0;end;ts=@2;R=@3;delay=@4;fil=@5;[num,den]=rcosine(1/td(1),1/ts(1),fil,R,delay);x=@6/2;')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'Mask Help','This block designs a raised cosine filter using the specified parameter. The filter is used to filter the input signal. You can optionally use the sinc filter in the filtering computation.')
set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'Mask Entries','1\/.05\/.5\/6\/''FIR/Sqrt''\/0\/')


%     Finished composite block ['Wurzel-Nyquist',13,'Filter'].

set_param([sys,'/',['Wurzel-Nyquist',13,'Filter']],...
		'position',[705,103,785,147])

add_block('built-in/Gain',[sys,'/','Gain1'])
set_param([sys,'/','Gain1'],...
		'Gain','1/4',...
		'position',[805,112,830,138])


%     Subsystem  ['Diagramme',13,'sendeseitig'].

new_system([sys,'/',['Diagramme',13,'sendeseitig']])
set_param([sys,'/',['Diagramme',13,'sendeseitig']],'Location',[475,310,844,551])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'sendeseitig/Constant1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Constant1']],...
		'Value','0',...
		'position',[130,130,150,150])

add_block('built-in/Step Fcn',[sys,'/',['Diagramme',13,'sendeseitig/Step input']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Step input']],...
		'Time','starttime',...
		'position',[35,85,55,105])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/in_1']],...
		'position',[35,40,55,60])

add_block('built-in/Switch',[sys,'/',['Diagramme',13,'sendeseitig/Switch']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Switch']],...
		'Threshold','1',...
		'position',[110,44,135,76])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'sendeseitig/Constant']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Constant']],...
		'Value','Inf',...
		'position',[35,130,55,150])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Mux1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Mux1']],...
		'inputs','2',...
		'position',[185,96,220,129])


%     Subsystem  ['Diagramme',13,'sendeseitig/Augendiagramm'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/in_1']],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Augendiagramm'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Augendiagramm']],...
		'position',[275,37,330,73])


%     Subsystem  ['Diagramme',13,'sendeseitig/Trajektorie'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_1']],...
		'position',[15,55,35,75])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_2']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/in_2']],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Mux']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Mux']],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie/Plot1']],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[40,65;45,65;45,80;60,80])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[45,125;50,125;60,95])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],[105,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Trajektorie'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Trajektorie']],...
		'position',[275,105,330,140])


%     Subsystem  ['Diagramme',13,'sendeseitig/Signalraumpunkte'].

new_system([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/in_1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/in_1']],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/Plot1']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block ['Diagramme',13,'sendeseitig/Signalraumpunkte'].

set_param([sys,'/',['Diagramme',13,'sendeseitig/Signalraumpunkte']],...
		'position',[275,173,330,207])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'sendeseitig/Mux']])
set_param([sys,'/',['Diagramme',13,'sendeseitig/Mux']],...
		'inputs','2',...
		'position',[185,36,220,69])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[140,60;180,60])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[150,60;150,105;180,105])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[155,140;165,140;165,45;180,45])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[165,120;180,120])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[225,115;270,115])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[250,115;250,190;270,190])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,140;95,140;105,70])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,95;75,95;75,60;105,60])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[60,50;105,50])
add_line([sys,'/',['Diagramme',13,'sendeseitig']],[225,55;270,55])
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','Diagramme')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','6\/40\/0\/')


%     Finished composite block ['Diagramme',13,'sendeseitig'].

set_param([sys,'/',['Diagramme',13,'sendeseitig']],...
		'position',[265,10,320,50])


%     Subsystem  ['Diagramme',13,'empfangsseitig'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],'Location',[475,310,844,551])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Mux']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Mux']],...
		'inputs','2',...
		'position',[185,36,220,69])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Signalraumpunkte'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte/in_1']],...
		'position',[75,80,95,100])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Signalraumpunkte'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Signalraumpunkte']],...
		'position',[275,173,330,207])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Trajektorie'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Plot1']],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Mux']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/Mux']],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_2']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_2']],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie/in_1']],...
		'position',[15,55,35,75])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[105,90;125,90])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[45,125;50,125;60,95])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],[40,65;45,65;45,80;60,80])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g.''\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Trajektorie'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Trajektorie']],...
		'position',[275,105,330,140])


%     Subsystem  ['Diagramme',13,'empfangsseitig/Augendiagramm'].

new_system([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/Plot1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/Plot1']],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm/in_1']],...
		'position',[75,80,95,100])
add_line([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],[100,90;125,90])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig/Augendiagramm'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig/Augendiagramm']],...
		'position',[275,37,330,73])

add_block('built-in/Mux',[sys,'/',['Diagramme',13,'empfangsseitig/Mux1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Mux1']],...
		'inputs','2',...
		'position',[185,96,220,129])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'empfangsseitig/Constant']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Constant']],...
		'Value','Inf',...
		'position',[35,130,55,150])

add_block('built-in/Switch',[sys,'/',['Diagramme',13,'empfangsseitig/Switch']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Switch']],...
		'Threshold','1',...
		'position',[110,44,135,76])

add_block('built-in/Inport',[sys,'/',['Diagramme',13,'empfangsseitig/in_1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/in_1']],...
		'position',[35,40,55,60])

add_block('built-in/Step Fcn',[sys,'/',['Diagramme',13,'empfangsseitig/Step input']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Step input']],...
		'Time','starttime',...
		'position',[35,85,55,105])

add_block('built-in/Constant',[sys,'/',['Diagramme',13,'empfangsseitig/Constant1']])
set_param([sys,'/',['Diagramme',13,'empfangsseitig/Constant1']],...
		'Value','0',...
		'position',[130,130,150,150])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[225,55;270,55])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,50;105,50])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,95;75,95;75,60;105,60])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[60,140;95,140;105,70])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[225,115;270,115])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[250,115;250,190;270,190])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[155,140;165,140;165,45;180,45])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[165,120;180,120])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[140,60;180,60])
add_line([sys,'/',['Diagramme',13,'empfangsseitig']],[150,60;150,105;180,105])
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','Diagramme')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','12\/40\/0\/')


%     Finished composite block ['Diagramme',13,'empfangsseitig'].

set_param([sys,'/',['Diagramme',13,'empfangsseitig']],...
		'position',[880,10,935,50])

add_block('built-in/Fcn',[sys,'/','Fcn'])
set_param([sys,'/','Fcn'],...
		'hide name',0,...
		'Expr','2*cos(4*pi*u)',...
		'position',[525,22,620,48])

add_block('built-in/Clock',[sys,'/','Clock1'])
set_param([sys,'/','Clock1'],...
		'hide name',0,...
		'position',[485,25,505,45])


%     Subsystem  'Doppelklick2'.

new_system([sys,'/','Doppelklick2'])
set_param([sys,'/','Doppelklick2'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick2'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Doppelklick2'.

set_param([sys,'/','Doppelklick2'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[480,75,615,101])
add_line(sys,[260,160;270,160])
add_line(sys,[625,35;635,120])
add_line(sys,[510,35;520,35])
add_line(sys,[925,125;985,125])
add_line(sys,[375,160;380,160;380,135;395,135])
add_line(sys,[435,130;500,130])
add_line(sys,[590,130;635,130])
add_line(sys,[45,125;80,125])
add_line(sys,[675,125;700,125])
add_line(sys,[215,125;395,125])
add_line(sys,[170,125;180,125])
add_line(sys,[790,125;800,125])
add_line(sys,[835,125;885,125])
add_line(sys,[950,125;950,225])
add_line(sys,[60,125;60,255;875,255;875,215;910,225])
add_line(sys,[60,220;80,220])
add_line(sys,[225,125;225,200])
add_line(sys,[835,125;845,125;845,175])
add_line(sys,[845,125;845,30;875,30])
add_line(sys,[690,125;690,175])
add_line(sys,[460,130;460,175])
add_line(sys,[600,130;600,210])
add_line(sys,[225,125;225,30;260,30])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
