function [ret,x0,str,ts,xts]=msk(t,x,u,flag);
%MSK	is the M-file description of the SIMULINK system named MSK.
%	The block-diagram can be displayed by typing: MSK.
%
%	SYS=MSK(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes MSK to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling MSK with a FLAG of zero:
%	[SIZES]=MSK([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = mfilename;
new_system(sys)
simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[251,42,1260,321])
     open_system(sys)
end;
set_param(sys,'algorithm',     'RK-45')
set_param(sys,'Start time',    '0.0')
set_param(sys,'Stop time',     '999999')
set_param(sys,'Min step size', '.025')
set_param(sys,'Max step size', '.025')
set_param(sys,'Relative error','1')
set_param(sys,'Return vars',   '')


%     Subsystem  'Kanal'.

new_system([sys,'/','Kanal'])
set_param([sys,'/','Kanal'],'Location',[11,262,273,408])


%     Subsystem  ['Kanal/Gaussian noise',13,'generator'].

new_system([sys,'/',['Kanal/Gaussian noise',13,'generator']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],'Location',[22,119,370,243])

add_block('built-in/Outport',[sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']],...
		'position',[285,60,305,80])

add_block('built-in/Sum',[sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']],...
		'position',[220,60,240,80])

add_block('built-in/Constant',[sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']],...
		'Value','m',...
		'position',[140,20,160,40])

add_block('built-in/White Noise',[sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']],...
		'Seed','s',...
		'position',[35,57,80,93])

add_block('built-in/State-Space',[sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'Mask Display','K',...
		'Mask Type','Matrix Gain',...
		'Mask Dialogue','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'Mask Translate','K = @1;',...
		'Mask Help','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'Mask Entries','d\/')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'position',[140,61,165,89])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[85,75;135,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[170,75;215,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[245,70;280,70])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[165,30;190,30;190,65;215,65])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Display','plot(0,0,100,100,x,y);Gaussian',...
		'Mask Type','Gaussian noise generator')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Dialogue','Generate Gaussian distributed noise with\ngiven mean and variance value.|Mean value:|Variance (vector or matrix):|Initial seed:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=srcsicon(3);')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Help','When the mean value and seed are vectors, the output of this block is a vector. The length of the vector is the same as the length of the mean value vector or the length of the seed. When the variance entry is a vector, the variance is a diagonal matrix.')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Entries','m\/d\/s\/')


%     Finished composite block ['Kanal/Gaussian noise',13,'generator'].

set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'position',[25,48,105,92])

add_block('built-in/Sum',[sys,'/','Kanal/Sum'])
set_param([sys,'/','Kanal/Sum'],...
		'position',[150,55,170,75])

add_block('built-in/Outport',[sys,'/','Kanal/out_1'])
set_param([sys,'/','Kanal/out_1'],...
		'position',[200,55,220,75])

add_block('built-in/Inport',[sys,'/','Kanal/in_1'])
set_param([sys,'/','Kanal/in_1'],...
		'position',[45,10,65,30])
add_line([sys,'/','Kanal'],[110,70;145,70])
add_line([sys,'/','Kanal'],[70,20;115,20;115,60;145,60])
add_line([sys,'/','Kanal'],[175,65;195,65])
set_param([sys,'/','Kanal'],...
		'Mask Display','plot(0,0,100,100,x,y);AWGN',...
		'Mask Type','AWGN channel, fixed parameter')
set_param([sys,'/','Kanal'],...
		'Mask Dialogue','Additive white Gaussian noise channel\nwith fixed mean and variance.|Mean value:|Variance (std^2):|Initial Seed:',...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=chanicon;')
set_param([sys,'/','Kanal'],...
		'Mask Help','This block adds white Gaussian noise to the input signal. The mean and the variance can be a scalar or vector with the same length as the input signal.',...
		'Mask Entries','0\/0.001\/12345\/')


%     Finished composite block 'Kanal'.

set_param([sys,'/','Kanal'],...
		'position',[465,83,545,127])


%     Subsystem  'Error rate'.

new_system([sys,'/','Error rate'])
set_param([sys,'/','Error rate'],'Location',[255,368,509,510])

add_block('built-in/S-Function',[sys,'/','Error rate/S-function'])
set_param([sys,'/','Error rate/S-function'],...
		'function name','sbiterr',...
		'parameters','num_lin, K, TDelay, Sample',...
		'position',[130,52,195,78])

add_block('built-in/Mux',[sys,'/','Error rate/Mux'])
set_param([sys,'/','Error rate/Mux'],...
		'inputs','2',...
		'position',[65,46,100,79])

add_block('built-in/Inport',[sys,'/','Error rate/in_1'])
set_param([sys,'/','Error rate/in_1'],...
		'position',[15,45,35,65])

add_block('built-in/Inport',[sys,'/','Error rate/in_2'])
set_param([sys,'/','Error rate/in_2'],...
		'Port','2',...
		'position',[15,60,35,80])
add_line([sys,'/','Error rate'],[105,65;125,65])
add_line([sys,'/','Error rate'],[40,55;60,55])
add_line([sys,'/','Error rate'],[40,70;60,70])
set_param([sys,'/','Error rate'],...
		'Mask Display','Error\nmeter',...
		'Mask Type','Symbol/bit error counter')
set_param([sys,'/','Error rate'],...
		'Mask Dialogue','Use the input data from the 1st port as the reference signal to detect the number of errors and error rate of the 2nd signal.|Bit per symbol:|Number of digits on display:|Delay between 1st port and 2nd port:|Sample time (sec):')
set_param([sys,'/','Error rate'],...
		'Mask Translate','K=@1;num_lin=@2;TDelay=@3;Sample=@4;')
set_param([sys,'/','Error rate'],...
		'Mask Help','The signal from the first port must be a scalar. The second input port can be a vector with a delay to the first port signal. The comparison happens only at the sampling point.')
set_param([sys,'/','Error rate'],...
		'Mask Entries','1\/10\/2\/1\/')


%     Finished composite block 'Error rate'.

set_param([sys,'/','Error rate'],...
		'orientation',1,...
		'position',[465,215,545,255])


%     Subsystem  'Signalraumkonstellation_'.

new_system([sys,'/','Signalraumkonstellation_'])
set_param([sys,'/','Signalraumkonstellation_'],'Location',[0,38,1264,980])
set_param([sys,'/','Signalraumkonstellation_'],...
		'Mask Display','Signalraum\nKonstellation',...
		'Mask Dialogue','eval(''figure''); eval(''modmap(''''psk'''',4)'')')


%     Finished composite block 'Signalraumkonstellation_'.

set_param([sys,'/','Signalraumkonstellation_'],...
		'BackGround',7,...
		'hide name',0,...
		'position',[55,15,140,51])


%     Subsystem  'Doppelklick2'.

new_system([sys,'/','Doppelklick2'])
set_param([sys,'/','Doppelklick2'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick2'],...
		'Mask Display','Zeige Sender',...
		'Mask Type','öffnen')
set_param([sys,'/','Doppelklick2'],...
		'Mask Dialogue','eval(''open_system(''''msk/Sender'''');open_system(''''msk/Sender/u(t)'''');open_system(''''msk/Sender/a(t)'''');open_system(''''msk/Sender/x_I(t)'''');open_system(''''msk/Sender/s_I(t)'''');open_system(''''msk/Sender/x_Q(t)'''');open_system(''''msk/Sender/s_Q(t)'''');open_system(''''msk/Sender/s(t)'''');open_system(''''msk/Sender/phi(t)'''')'')')


%     Finished composite block 'Doppelklick2'.

set_param([sys,'/','Doppelklick2'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[30,85,165,111])


%     Subsystem  'Doppelklick3'.

new_system([sys,'/','Doppelklick3'])
set_param([sys,'/','Doppelklick3'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick3'],...
		'Mask Display','Zeige Empfänger',...
		'Mask Type','öffnen')
set_param([sys,'/','Doppelklick3'],...
		'Mask Dialogue','eval(''open_system(''''msk/Empfänger'''');open_system(''''msk/Empfänger/r(t)'''');open_system(''''msk/Empfänger/x_eI(t)'''');open_system(''''msk/Empfänger/d_eI(t)'''');open_system(''''msk/Empfänger/x_eQ(t)'''');open_system(''''msk/Empfänger/d_eQ(t)'''');open_system(''''msk/Empfänger/y(t)'''');open_system(''''msk/Empfänger/v(t)'''');'')')


%     Finished composite block 'Doppelklick3'.

set_param([sys,'/','Doppelklick3'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[800,85,935,111])

add_block('built-in/Scope',[sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'orientation',3,...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','12.500000',...
		'Vmax','6.000000',...
		'Hmax','25.000000',...
		'Window',[360,340,1280,440])
open_system([sys,'/','u(t)'])
set_param([sys,'/','u(t)'],...
		'position',[320,25,350,55])

add_block('built-in/Scope',[sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'orientation',3,...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','12.500000',...
		'Vmax','6.000000',...
		'Hmax','25.000000',...
		'Window',[360,740,1280,840])
open_system([sys,'/','d_e(t)'])
set_param([sys,'/','d_e(t)'],...
		'position',[750,20,780,50])


%     Subsystem  'Empfänger'.

new_system([sys,'/','Empfänger'])
set_param([sys,'/','Empfänger'],'Location',[251,42,1259,320])

add_block('built-in/Inport',[sys,'/',['Empfänger/gestörtes',13,'MSK-',13,'Signal']])
set_param([sys,'/',['Empfänger/gestörtes',13,'MSK-',13,'Signal']],...
		'position',[20,120,40,140])

add_block('built-in/Scope',[sys,'/','Empfänger/r(t)'])
set_param([sys,'/','Empfänger/r(t)'],...
		'orientation',3,...
		'move name',0,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,340,1280,440],...
		'position',[45,20,75,50])

add_block('built-in/Fcn',[sys,'/','Empfänger/Fcn3'])
set_param([sys,'/','Empfänger/Fcn3'],...
		'hide name',0,...
		'Expr','2*cos(4*pi*u)',...
		'position',[130,105,225,125])

add_block('built-in/Fcn',[sys,'/','Empfänger/Fcn2'])
set_param([sys,'/','Empfänger/Fcn2'],...
		'hide name',0,...
		'Expr','-2*sin(4*pi*u)',...
		'position',[130,135,225,155])

add_block('built-in/Clock',[sys,'/','Empfänger/Clock'])
set_param([sys,'/','Empfänger/Clock'],...
		'hide name',0,...
		'position',[90,120,110,140])

add_block('built-in/Transport Delay',[sys,'/',['Empfänger/Transport',13,'Delay1']])
set_param([sys,'/',['Empfänger/Transport',13,'Delay1']],...
		'hide name',0,...
		'move name',0,...
		'Delay Time','.5',...
		'Buffer Size:','200',...
		'position',[420,65,460,95])

add_block('built-in/Transport Delay',[sys,'/',['Empfänger/Transport',13,'Delay']])
set_param([sys,'/',['Empfänger/Transport',13,'Delay']],...
		'hide name',0,...
		'move name',0,...
		'Delay Time','.5',...
		'Buffer Size:','200',...
		'position',[420,165,460,195])

add_block('built-in/Scope',[sys,'/','Empfänger/d_eQ(t)'])
set_param([sys,'/','Empfänger/d_eQ(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,732,1280,832],...
		'position',[465,230,495,260])

add_block('built-in/Scope',[sys,'/','Empfänger/d_eI(t)'])
set_param([sys,'/','Empfänger/d_eI(t)'],...
		'orientation',3,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,536,1280,636],...
		'position',[465,10,495,40])

add_block('built-in/Scope',[sys,'/','Empfänger/x_eI(t)'])
set_param([sys,'/','Empfänger/x_eI(t)'],...
		'orientation',3,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,437,1280,537],...
		'position',[290,10,320,40])

add_block('built-in/Product',[sys,'/','Empfänger/Product4'])
set_param([sys,'/','Empfänger/Product4'],...
		'hide name',0,...
		'position',[255,168,285,192])

add_block('built-in/Zero-Pole',[sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter_']])
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter_']],...
		'Zeros','z',...
		'Poles','p',...
		'Gain','k',...
		'Mask Display','plot(20*log10(w),20*log10(abs(h)))',...
		'Mask Type','buttap')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter_']],...
		'Mask Dialogue','Analog Butterworth low pass filter.\n\n(Requires Signal Processing Toolbox)|Cutoff frequency (rad/sec)|Order')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter_']],...
		'Mask Translate','[z,p,k]=buttap(@2); z=@1*z; p=@1*p; k=real(prod(-p)); [num,den]=zp2tf(z,p,k); w=logspace(log10(@1/10),log10(10*@1),20); h=freqs(num,den,w); ')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter_']],...
		'Mask Help','Butterworth low pass filter using MATLAB''s butter command.',...
		'Mask Entries','5\/4\/',...
		'position',[340,158,400,202])

add_block('built-in/Scope',[sys,'/','Empfänger/x_eQ(t)'])
set_param([sys,'/','Empfänger/x_eQ(t)'],...
		'orientation',1,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,634,1280,734],...
		'position',[285,230,315,260])

add_block('built-in/Zero-Pole',[sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter']])
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter']],...
		'Zeros','z',...
		'Poles','p',...
		'Gain','k',...
		'Mask Display','plot(20*log10(w),20*log10(abs(h)))',...
		'Mask Type','buttap')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter']],...
		'Mask Dialogue','Analog Butterworth low pass filter.\n\n(Requires Signal Processing Toolbox)|Cutoff frequency (rad/sec)|Order')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter']],...
		'Mask Translate','[z,p,k]=buttap(@2); z=@1*z; p=@1*p; k=real(prod(-p)); [num,den]=zp2tf(z,p,k); w=logspace(log10(@1/10),log10(10*@1),20); h=freqs(num,den,w); ')
set_param([sys,'/',['Empfänger/Analog Butterworth',13,'LP Filter']],...
		'Mask Help','Butterworth low pass filter using MATLAB''s butter command.',...
		'Mask Entries','5\/4\/',...
		'position',[340,58,400,102])

add_block('built-in/Product',[sys,'/','Empfänger/Product3'])
set_param([sys,'/','Empfänger/Product3'],...
		'hide name',0,...
		'position',[255,68,285,92])

add_block('built-in/Outport',[sys,'/',['Empfänger/empfangenes',13,'Bit']])
set_param([sys,'/',['Empfänger/empfangenes',13,'Bit']],...
		'Port','2',...
		'position',[955,195,975,215])


%     Subsystem  'Empfänger/Doppelklick4'.

new_system([sys,'/','Empfänger/Doppelklick4'])
set_param([sys,'/','Empfänger/Doppelklick4'],'Location',[136,230,381,439])
set_param([sys,'/','Empfänger/Doppelklick4'],...
		'Mask Display','Schließe Empfänger',...
		'Mask Type','schließen')
set_param([sys,'/','Empfänger/Doppelklick4'],...
		'Mask Dialogue','eval(''close_system(''''msk/Empfänger'''');close_system(''''msk/Empfänger/r(t)'''');close_system(''''msk/Empfänger/x_eI(t)'''');close_system(''''msk/Empfänger/d_eI(t)'''');close_system(''''msk/Empfänger/x_eQ(t)'''');close_system(''''msk/Empfänger/d_eQ(t)'''');close_system(''''msk/Empfänger/y(t)'''');close_system(''''msk/Empfänger/v(t)'''');'')')


%     Finished composite block 'Empfänger/Doppelklick4'.

set_param([sys,'/','Empfänger/Doppelklick4'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[840,10,975,36])

add_block('built-in/Scope',[sys,'/','Empfänger/v(t)'])
set_param([sys,'/','Empfänger/v(t)'],...
		'orientation',3,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,924,1280,1024],...
		'position',[905,60,935,90])


%     Subsystem  ['Empfänger/Pulse',13,'Generator1'].

new_system([sys,'/',['Empfänger/Pulse',13,'Generator1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],'Location',[158,441,759,682])

add_block('built-in/Unit Delay',[sys,'/',['Empfänger/Pulse',13,'Generator1/Unit Delay1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])

add_block('built-in/Unit Delay',[sys,'/',['Empfänger/Pulse',13,'Generator1/Unit Delay']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Constant',[sys,'/',['Empfänger/Pulse',13,'Generator1/Constant']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Sum',[sys,'/',['Empfänger/Pulse',13,'Generator1/Sum']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Sum',[sys,'/',['Empfänger/Pulse',13,'Generator1/Sum1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Pulse',13,'Generator1/Relational',13,'operator']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Clock',[sys,'/',['Empfänger/Pulse',13,'Generator1/Clock1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Constant',[sys,'/',['Empfänger/Pulse',13,'Generator1/Constant1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Logical Operator',[sys,'/',['Empfänger/Pulse',13,'Generator1/Logical',13,'Operator']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Logical Operator',[sys,'/',['Empfänger/Pulse',13,'Generator1/Logical',13,'Operator1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Product',[sys,'/',['Empfänger/Pulse',13,'Generator1/Product']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Gain',[sys,'/',['Empfänger/Pulse',13,'Generator1/Gain']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Outport',[sys,'/',['Empfänger/Pulse',13,'Generator1/out_1']])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[155,130;245,130;245,55;280,55])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[160,45;280,45])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[50,40;130,40])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[320,110;365,110])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[405,120;450,120])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[485,115;505,115])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[540,115;555,115])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[320,50;350,50])
add_line([sys,'/',['Empfänger/Pulse',13,'Generator1']],[390,50;430,50;430,110;450,110])
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'Mask Entries','2\/1\/1\/0\/')


%     Finished composite block ['Empfänger/Pulse',13,'Generator1'].

set_param([sys,'/',['Empfänger/Pulse',13,'Generator1']],...
		'hide name',0,...
		'position',[560,112,595,148])

add_block('built-in/Switch',[sys,'/','Empfänger/Schalter'])
set_param([sys,'/','Empfänger/Schalter'],...
		'Threshold','1',...
		'position',[625,114,655,146])

add_block('built-in/Step Fcn',[sys,'/','Empfänger/Step Input'])
set_param([sys,'/','Empfänger/Step Input'],...
		'Time','2',...
		'position',[745,195,765,215])

add_block('built-in/Constant',[sys,'/','Empfänger/Constant'])
set_param([sys,'/','Empfänger/Constant'],...
		'orientation',2,...
		'position',[805,195,825,215])

add_block('built-in/Zero-Order Hold',[sys,'/','Empfänger/Halten'])
set_param([sys,'/','Empfänger/Halten'],...
		'position',[735,114,770,146])


%     Subsystem  ['Empfänger/Schwell-',13,'wert'].

new_system([sys,'/',['Empfänger/Schwell-',13,'wert']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert']],'Location',[159,417,467,586])

add_block('built-in/Outport',[sys,'/',['Empfänger/Schwell-',13,'wert/out_1']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/out_1']],...
		'position',[265,70,285,90])

add_block('built-in/Inport',[sys,'/',['Empfänger/Schwell-',13,'wert/in_1']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/in_1']],...
		'position',[35,30,55,50])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwell-',13,'wert/Relational',13,'Operator']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/Relational',13,'Operator']],...
		'Operator','>',...
		'position',[140,32,170,63])

add_block('built-in/Sum',[sys,'/',['Empfänger/Schwell-',13,'wert/Sum']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/Sum']],...
		'inputs','+-',...
		'position',[215,64,235,91])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwell-',13,'wert/Relational',13,'Operator1']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/Relational',13,'Operator1']],...
		'Operator','<',...
		'position',[140,92,170,123])

add_block('built-in/Constant',[sys,'/',['Empfänger/Schwell-',13,'wert/Constant']])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert/Constant']],...
		'Value','0',...
		'position',[65,105,85,125])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[60,40;135,40])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[95,40;95,100;135,100])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[90,115;135,115])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[110,115;110,55;135,55])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[175,110;185,110;185,85;210,85])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[175,50;185,50;185,70;210,70])
add_line([sys,'/',['Empfänger/Schwell-',13,'wert']],[240,80;260,80])
set_param([sys,'/',['Empfänger/Schwell-',13,'wert']],...
		'Mask Display','plot(-50,-50,50,50,[-50,50],[0,0],[0,0],[-50,50],[-40,0],[-30,-30],[0,40],[30,30])',...
		'Mask Type','Sign',...
		'Mask Dialogue','y = sign(x)')
set_param([sys,'/',['Empfänger/Schwell-',13,'wert']],...
		'Mask Help','Sign Function:\n\t\t\ty = 1 if x > 0\n\t\t\ty = 0 if x = 0\n\t\t\ty = -1 if x < 0')


%     Finished composite block ['Empfänger/Schwell-',13,'wert'].

set_param([sys,'/',['Empfänger/Schwell-',13,'wert']],...
		'position',[680,113,710,147])

add_block('built-in/Scope',[sys,'/','Empfänger/y(t)'])
set_param([sys,'/','Empfänger/y(t)'],...
		'orientation',3,...
		'Vgain','2.000000',...
		'Hgain','25.000000',...
		'Vmax','4.000000',...
		'Hmax','50.000000',...
		'Window',[360,830,1280,930],...
		'position',[835,60,865,90])


%     Subsystem  'Empfänger/Decodierung'.

new_system([sys,'/','Empfänger/Decodierung'])
set_param([sys,'/','Empfänger/Decodierung'],'Location',[587,391,914,649])

add_block('built-in/Inport',[sys,'/','Empfänger/Decodierung/in_1'])
set_param([sys,'/','Empfänger/Decodierung/in_1'],...
		'position',[20,25,40,45])

add_block('built-in/Product',[sys,'/','Empfänger/Decodierung/Product'])
set_param([sys,'/','Empfänger/Decodierung/Product'],...
		'hide name',0,...
		'position',[155,28,185,52])

add_block('built-in/Product',[sys,'/','Empfänger/Decodierung/Product1'])
set_param([sys,'/','Empfänger/Decodierung/Product1'],...
		'hide name',0,...
		'position',[90,138,120,162])

add_block('built-in/Scope',[sys,'/','Empfänger/Decodierung/a(t-1)'])
set_param([sys,'/','Empfänger/Decodierung/a(t-1)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[371,799,1284,899],...
		'position',[165,135,195,165])

add_block('built-in/Fcn',[sys,'/','Empfänger/Decodierung/Fcn4'])
set_param([sys,'/','Empfänger/Decodierung/Fcn4'],...
		'orientation',2,...
		'hide name',0,...
		'Expr','1-2*u',...
		'position',[70,215,130,235])


%     Subsystem  ['Empfänger/Decodierung/Pulse',13,'Generator'].

new_system([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],'Location',[158,441,759,682])

add_block('built-in/Outport',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/out_1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])

add_block('built-in/Gain',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Gain']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Product',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Product']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Logical Operator',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Logical',13,'Operator1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Logical Operator',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Logical',13,'Operator']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Constant',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Constant1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Clock',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Clock1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Relational',13,'operator']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Sum',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Sum1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Sum',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Sum']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Constant',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Constant']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Unit Delay',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Unit Delay']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Unit Delay',[sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Unit Delay1']])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[390,50;430,50;430,110;450,110])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[320,50;350,50])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[540,115;555,115])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[485,115;505,115])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[405,120;450,120])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[320,110;365,110])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[50,40;130,40])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[160,45;280,45])
add_line([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],[155,130;245,130;245,55;280,55])
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'Mask Entries','2\/1\/1\/0\/')


%     Finished composite block ['Empfänger/Decodierung/Pulse',13,'Generator'].

set_param([sys,'/',['Empfänger/Decodierung/Pulse',13,'Generator']],...
		'orientation',2,...
		'hide name',0,...
		'position',[160,207,195,243])

add_block('built-in/Outport',[sys,'/','Empfänger/Decodierung/Bit'])
set_param([sys,'/','Empfänger/Decodierung/Bit'],...
		'Port','2',...
		'position',[290,85,310,105])

add_block('built-in/Unit Delay',[sys,'/','Empfänger/Decodierung/Unit Delay'])
set_param([sys,'/','Empfänger/Decodierung/Unit Delay'],...
		'orientation',1,...
		'hide name',0,...
		'x0','1',...
		'position',[45,85,95,105])

add_block('built-in/Outport',[sys,'/','Empfänger/Decodierung/out_1'])
set_param([sys,'/','Empfänger/Decodierung/out_1'],...
		'position',[290,30,310,50])

add_block('built-in/Fcn',[sys,'/','Empfänger/Decodierung/Fcn5'])
set_param([sys,'/','Empfänger/Decodierung/Fcn5'],...
		'hide name',0,...
		'Expr','(1-u)/2',...
		'position',[210,85,270,105])
add_line([sys,'/','Empfänger/Decodierung'],[70,110;70,145;85,145])
add_line([sys,'/','Empfänger/Decodierung'],[125,150;160,150])
add_line([sys,'/','Empfänger/Decodierung'],[45,35;150,35])
add_line([sys,'/','Empfänger/Decodierung'],[190,40;285,40])
add_line([sys,'/','Empfänger/Decodierung'],[135,150;135,45;150,45])
add_line([sys,'/','Empfänger/Decodierung'],[70,35;70,80])
add_line([sys,'/','Empfänger/Decodierung'],[155,225;135,225])
add_line([sys,'/','Empfänger/Decodierung'],[65,225;45,225;45,155;85,155])
add_line([sys,'/','Empfänger/Decodierung'],[275,95;285,95])
add_line([sys,'/','Empfänger/Decodierung'],[190,40;190,95;205,95])


%     Finished composite block 'Empfänger/Decodierung'.

set_param([sys,'/','Empfänger/Decodierung'],...
		'position',[865,110,895,165])

add_block('built-in/Outport',[sys,'/',['Empfänger/empfangenes',13,'Symbol']])
set_param([sys,'/',['Empfänger/empfangenes',13,'Symbol']],...
		'position',[955,115,975,135])

add_block('built-in/Switch',[sys,'/','Empfänger/Schalter1'])
set_param([sys,'/','Empfänger/Schalter1'],...
		'hide name',0,...
		'Threshold','1',...
		'position',[805,124,835,156])


%     Subsystem  'Empfänger/Diagramme'.

new_system([sys,'/','Empfänger/Diagramme'])
set_param([sys,'/','Empfänger/Diagramme'],'Location',[669,447,1065,724])


%     Subsystem  'Empfänger/Diagramme/Auge Quadratur'.

new_system([sys,'/','Empfänger/Diagramme/Auge Quadratur'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Auge Quadratur/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Auge Quadratur/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Empfänger/Diagramme/Auge Quadratur'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Empfänger/Diagramme/Auge Quadratur'.

set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'position',[305,77,360,113])


%     Subsystem  'Empfänger/Diagramme/Auge Inphase'.

new_system([sys,'/','Empfänger/Diagramme/Auge Inphase'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Auge Inphase/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Auge Inphase/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Auge Inphase'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Empfänger/Diagramme/Auge Inphase'.

set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'position',[305,22,360,58])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux'])
set_param([sys,'/','Empfänger/Diagramme/Mux'],...
		'inputs','2',...
		'position',[230,21,265,54])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux1'])
set_param([sys,'/','Empfänger/Diagramme/Mux1'],...
		'inputs','2',...
		'position',[230,76,265,109])

add_block('built-in/Constant',[sys,'/','Empfänger/Diagramme/Constant'])
set_param([sys,'/','Empfänger/Diagramme/Constant'],...
		'orientation',3,...
		'hide name',0,...
		'Value','Inf',...
		'position',[90,125,110,145])

add_block('built-in/Constant',[sys,'/','Empfänger/Diagramme/Constant0'])
set_param([sys,'/','Empfänger/Diagramme/Constant0'],...
		'orientation',3,...
		'hide name',0,...
		'Value','0',...
		'position',[190,125,210,145])


%     Subsystem  'Empfänger/Diagramme/Trajektorie'.

new_system([sys,'/','Empfänger/Diagramme/Trajektorie'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Trajektorie/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/in_1'],...
		'position',[15,55,35,75])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Trajektorie/in_2'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/in_2'],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Trajektorie/Mux'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/Mux'],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Trajektorie/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/Plot1'],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[40,65;45,65;45,80;60,80])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[45,125;50,125;60,95])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[105,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block 'Empfänger/Diagramme/Trajektorie'.

set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'position',[305,155,360,190])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux2'])
set_param([sys,'/','Empfänger/Diagramme/Mux2'],...
		'inputs','2',...
		'position',[230,146,265,179])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux3'])
set_param([sys,'/','Empfänger/Diagramme/Mux3'],...
		'inputs','2',...
		'position',[230,211,265,244])


%     Subsystem  'Empfänger/Diagramme/Signalraumpunkte'.

new_system([sys,'/','Empfänger/Diagramme/Signalraumpunkte'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Signalraumpunkte/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Signalraumpunkte/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block 'Empfänger/Diagramme/Signalraumpunkte'.

set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'position',[305,213,360,247])

add_block('built-in/Step Fcn',[sys,'/','Empfänger/Diagramme/Step input'])
set_param([sys,'/','Empfänger/Diagramme/Step input'],...
		'Time','starttime',...
		'position',[30,125,50,145])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Quadratur'])
set_param([sys,'/','Empfänger/Diagramme/Quadratur'],...
		'Port','2',...
		'position',[30,80,50,100])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Inphase'])
set_param([sys,'/','Empfänger/Diagramme/Inphase'],...
		'position',[30,25,50,45])

add_block('built-in/Switch',[sys,'/','Empfänger/Diagramme/Switch1'])
set_param([sys,'/','Empfänger/Diagramme/Switch1'],...
		'Threshold','1',...
		'position',[130,84,155,116])

add_block('built-in/Switch',[sys,'/','Empfänger/Diagramme/Switch'])
set_param([sys,'/','Empfänger/Diagramme/Switch'],...
		'Threshold','1',...
		'position',[130,29,155,61])
add_line([sys,'/','Empfänger/Diagramme'],[160,45;170,45;170,220;225,220])
add_line([sys,'/','Empfänger/Diagramme'],[170,45;225,45])
add_line([sys,'/','Empfänger/Diagramme'],[160,100;180,100;180,235;225,235])
add_line([sys,'/','Empfänger/Diagramme'],[180,100;225,100])
add_line([sys,'/','Empfänger/Diagramme'],[200,120;200,85;225,85])
add_line([sys,'/','Empfänger/Diagramme'],[200,85;200,30;225,30])
add_line([sys,'/','Empfänger/Diagramme'],[180,170;225,170])
add_line([sys,'/','Empfänger/Diagramme'],[170,155;225,155])
add_line([sys,'/','Empfänger/Diagramme'],[55,90;125,90])
add_line([sys,'/','Empfänger/Diagramme'],[55,35;125,35])
add_line([sys,'/','Empfänger/Diagramme'],[55,135;75,135;75,45;125,45])
add_line([sys,'/','Empfänger/Diagramme'],[75,100;125,100])
add_line([sys,'/','Empfänger/Diagramme'],[100,120;100,55;125,55])
add_line([sys,'/','Empfänger/Diagramme'],[100,110;125,110])
add_line([sys,'/','Empfänger/Diagramme'],[270,95;300,95])
add_line([sys,'/','Empfänger/Diagramme'],[270,40;300,40])
add_line([sys,'/','Empfänger/Diagramme'],[270,230;300,230])
add_line([sys,'/','Empfänger/Diagramme'],[270,165;300,165])
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','2D-Diagramme')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','2\/40\/0.075\/')


%     Finished composite block 'Empfänger/Diagramme'.

set_param([sys,'/','Empfänger/Diagramme'],...
		'position',[580,10,635,50])


%     Subsystem  'Empfänger/Doppelklick5'.

new_system([sys,'/','Empfänger/Doppelklick5'])
set_param([sys,'/','Empfänger/Doppelklick5'],'Location',[136,230,381,439])
set_param([sys,'/','Empfänger/Doppelklick5'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Empfänger/Doppelklick5'.

set_param([sys,'/','Empfänger/Doppelklick5'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[10,195,145,221])
add_line([sys,'/','Empfänger'],[230,115;235,115;235,85;250,85])
add_line([sys,'/','Empfänger'],[115,130;125,115])
add_line([sys,'/','Empfänger'],[115,130;125,145])
add_line([sys,'/','Empfänger'],[290,80;305,80;305,45])
add_line([sys,'/','Empfänger'],[305,80;335,80])
add_line([sys,'/','Empfänger'],[290,180;335,180])
add_line([sys,'/','Empfänger'],[230,145;235,145;235,175;250,175])
add_line([sys,'/','Empfänger'],[600,130;620,130])
add_line([sys,'/','Empfänger'],[45,130;80,130;80,185;250,185])
add_line([sys,'/','Empfänger'],[900,125;950,125])
add_line([sys,'/','Empfänger'],[300,180;300,225])
add_line([sys,'/','Empfänger'],[660,130;675,130])
add_line([sys,'/','Empfänger'],[405,180;415,180])
add_line([sys,'/','Empfänger'],[465,180;605,180;605,140;620,140])
add_line([sys,'/','Empfänger'],[480,180;480,225])
add_line([sys,'/','Empfänger'],[405,80;415,80])
add_line([sys,'/','Empfänger'],[465,80;605,80;605,120;620,120])
add_line([sys,'/','Empfänger'],[480,80;480,45])
add_line([sys,'/','Empfänger'],[800,205;790,205;800,150])
add_line([sys,'/','Empfänger'],[770,205;780,205;780,140;800,140])
add_line([sys,'/','Empfänger'],[60,130;60,55])
add_line([sys,'/','Empfänger'],[80,130;80,75;250,75])
add_line([sys,'/','Empfänger'],[550,180;550,40;575,40])
add_line([sys,'/','Empfänger'],[535,80;535,20;575,20])
add_line([sys,'/','Empfänger'],[715,130;730,130])
add_line([sys,'/','Empfänger'],[775,130;800,130])
add_line([sys,'/','Empfänger'],[900,150;925,150;925,205;950,205])
add_line([sys,'/','Empfänger'],[920,125;920,95])
add_line([sys,'/','Empfänger'],[840,140;860,140])
add_line([sys,'/','Empfänger'],[850,140;850,95])


%     Finished composite block 'Empfänger'.

set_param([sys,'/','Empfänger'],...
		'position',[645,59,720,146])

add_block('built-in/Scope',[sys,'/','phi(t)'])
set_param([sys,'/','phi(t)'],...
		'orientation',1,...
		'move name',0,...
		'Vgain','3.141590',...
		'Hgain','12.500000',...
		'Vmax','6.283180',...
		'Hmax','25.000000',...
		'Window',[360,440,1280,540])
open_system([sys,'/','phi(t)'])
set_param([sys,'/','phi(t)'],...
		'position',[285,185,315,215])


%     Subsystem  'Sender'.

new_system([sys,'/','Sender'])
set_param([sys,'/','Sender'],'Location',[251,42,1260,320])


%     Subsystem  'Sender/Quelle'.

new_system([sys,'/','Sender/Quelle'])
set_param([sys,'/','Sender/Quelle'],'Location',[56,430,318,576])

add_block('built-in/Outport',[sys,'/','Sender/Quelle/Symbol'])
set_param([sys,'/','Sender/Quelle/Symbol'],...
		'Port','2',...
		'position',[200,70,220,90])

add_block('built-in/Fcn',[sys,'/','Sender/Quelle/Fcn'])
set_param([sys,'/','Sender/Quelle/Fcn'],...
		'Expr','1-2*u',...
		'position',[130,70,170,90])

add_block('built-in/Outport',[sys,'/','Sender/Quelle/Binärsignal'])
set_param([sys,'/','Sender/Quelle/Binärsignal'],...
		'position',[200,25,220,45])


%     Subsystem  'Sender/Quelle/Quelle'.

new_system([sys,'/','Sender/Quelle/Quelle'])
set_param([sys,'/','Sender/Quelle/Quelle'],'Location',[355,528,737,675])

add_block('built-in/S-Function',[sys,'/','Sender/Quelle/Quelle/Message source'])
set_param([sys,'/','Sender/Quelle/Quelle/Message source'],...
		'BackGround',5,...
		'function name','trigwksp',...
		'parameters','var,thd,cyclFlag,ini',...
		'Mask Display','Triggered\nread',...
		'Mask Type','Read from workspace')
set_param([sys,'/','Sender/Quelle/Quelle/Message source'],...
		'Mask Dialogue','The raising edge of input pulse trigger the block output the next row from the workspace variable.|Read the variable:|Threshold for the input pulse:|Cyclic read variable (1) or amend zeros (0).|Output before first trigger:')
set_param([sys,'/','Sender/Quelle/Quelle/Message source'],...
		'Mask Translate','var=@1;thd=@2;cyclFlag=@3;ini=@4;')
set_param([sys,'/','Sender/Quelle/Quelle/Message source'],...
		'Mask Help','This block reads the data from a workspace variable. The output is refreshed at the raising edge of the input pulse.',...
		'Mask Entries','var\/.1\/cyc\/ini\/')
set_param([sys,'/','Sender/Quelle/Quelle/Message source'],...
		'position',[180,53,255,97])

add_block('built-in/Outport',[sys,'/','Sender/Quelle/Quelle/out_1'])
set_param([sys,'/','Sender/Quelle/Quelle/out_1'],...
		'position',[295,65,315,85])


%     Subsystem  ['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/Outport',[sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])

add_block('built-in/S-Function',[sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])
add_line([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','ts\/1\/off\/')


%     Finished composite block ['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Sender/Quelle/Quelle/Pulses deivide',13,'same sample time1']],...
		'position',[50,56,110,94])
add_line([sys,'/','Sender/Quelle/Quelle'],[115,75;175,75])
add_line([sys,'/','Sender/Quelle/Quelle'],[260,75;290,75])
set_param([sys,'/','Sender/Quelle/Quelle'],...
		'Mask Display','plot(0,0,100,100,x,y);Rd wksp',...
		'Mask Type','Read from workspace')
set_param([sys,'/','Sender/Quelle/Quelle'],...
		'Mask Dialogue','Read from a workspace variable at\nsampling time point.|Variable (column_number=block_output_length):|Data output sample time (sec):|Repeat flag (1: repeat read, 0: output zeros after eof).|Initial output:')
set_param([sys,'/','Sender/Quelle/Quelle'],...
		'Mask Translate','var=@1;td=@2;ts=td(1);if (length(td)>=2),off=td(2);else off=0;end;cyc=@3;ini=@4;[x,y]=srcsicon(7);')
set_param([sys,'/','Sender/Quelle/Quelle'],...
		'Mask Help','This block reads from a workspace variable at a given sample time. The column number is the block output vector length. When the simulation reaches the end of the variable (eof), the block will cyclically output from the first row of the variable or output zeros based on the repeat flag entree.')
set_param([sys,'/','Sender/Quelle/Quelle'],...
		'Mask Entries','randint(1000,1,2)\/1\/1\/1\/')


%     Finished composite block 'Sender/Quelle/Quelle'.

set_param([sys,'/','Sender/Quelle/Quelle'],...
		'position',[25,58,90,102])
add_line([sys,'/','Sender/Quelle'],[95,80;125,80])
add_line([sys,'/','Sender/Quelle'],[175,80;195,80])
add_line([sys,'/','Sender/Quelle'],[110,80;110,35;195,35])


%     Finished composite block 'Sender/Quelle'.

set_param([sys,'/','Sender/Quelle'],...
		'position',[20,90,50,145])

add_block('built-in/Outport',[sys,'/','Sender/Symbol'])
set_param([sys,'/','Sender/Symbol'],...
		'position',[100,215,120,235])


%     Subsystem  'Sender/Vorcodierung'.

new_system([sys,'/','Sender/Vorcodierung'])
set_param([sys,'/','Sender/Vorcodierung'],'Location',[163,347,403,607])

add_block('built-in/Scope',[sys,'/','Sender/Vorcodierung/a(t-1)'])
set_param([sys,'/','Sender/Vorcodierung/a(t-1)'],...
		'orientation',2,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[354,304,1267,404],...
		'position',[25,135,55,165])

add_block('built-in/Product',[sys,'/','Sender/Vorcodierung/Product1'])
set_param([sys,'/','Sender/Vorcodierung/Product1'],...
		'orientation',2,...
		'hide name',0,...
		'position',[115,138,145,162])

add_block('built-in/Product',[sys,'/','Sender/Vorcodierung/Product'])
set_param([sys,'/','Sender/Vorcodierung/Product'],...
		'hide name',0,...
		'position',[110,28,140,52])

add_block('built-in/Unit Delay',[sys,'/','Sender/Vorcodierung/Unit Delay'])
set_param([sys,'/','Sender/Vorcodierung/Unit Delay'],...
		'orientation',1,...
		'hide name',0,...
		'x0','1',...
		'position',[135,90,185,110])

add_block('built-in/Inport',[sys,'/','Sender/Vorcodierung/in_1'])
set_param([sys,'/','Sender/Vorcodierung/in_1'],...
		'position',[30,25,50,45])

add_block('built-in/Outport',[sys,'/','Sender/Vorcodierung/out_1'])
set_param([sys,'/','Sender/Vorcodierung/out_1'],...
		'position',[190,30,210,50])


%     Subsystem  ['Sender/Vorcodierung/Pulse',13,'Generator'].

new_system([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],'Location',[158,441,759,682])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Unit Delay1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Unit Delay']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Constant',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Constant']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Sum',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Sum']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Sum',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Sum1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Relational Operator',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Relational',13,'operator']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Clock',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Clock1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Constant',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Constant1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Logical',13,'Operator']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Logical',13,'Operator1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Product',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Product']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Gain',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Gain']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Outport',[sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/out_1']])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[155,130;245,130;245,55;280,55])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[160,45;280,45])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[50,40;130,40])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[320,110;365,110])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[405,120;450,120])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[485,115;505,115])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[540,115;555,115])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[320,50;350,50])
add_line([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],[390,50;430,50;430,110;450,110])
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'Mask Entries','2\/1\/1\/0\/')


%     Finished composite block ['Sender/Vorcodierung/Pulse',13,'Generator'].

set_param([sys,'/',['Sender/Vorcodierung/Pulse',13,'Generator']],...
		'hide name',0,...
		'position',[25,202,60,238])

add_block('built-in/Fcn',[sys,'/','Sender/Vorcodierung/Fcn4'])
set_param([sys,'/','Sender/Vorcodierung/Fcn4'],...
		'hide name',0,...
		'Expr','1-2*u',...
		'position',[80,209,140,231])
add_line([sys,'/','Sender/Vorcodierung'],[110,150;60,150])
add_line([sys,'/','Sender/Vorcodierung'],[85,150;85,45;105,45])
add_line([sys,'/','Sender/Vorcodierung'],[145,40;185,40])
add_line([sys,'/','Sender/Vorcodierung'],[160,40;160,85])
add_line([sys,'/','Sender/Vorcodierung'],[55,35;105,35])
add_line([sys,'/','Sender/Vorcodierung'],[160,115;150,145])
add_line([sys,'/','Sender/Vorcodierung'],[65,220;75,220])
add_line([sys,'/','Sender/Vorcodierung'],[145,220;160,220;150,155])


%     Finished composite block 'Sender/Vorcodierung'.

set_param([sys,'/','Sender/Vorcodierung'],...
		'position',[140,103,170,157])

add_block('built-in/Scope',[sys,'/','Sender/s(t)'])
set_param([sys,'/','Sender/s(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[358,838,1280,938],...
		'position',[885,65,915,95])

add_block('built-in/Scope',[sys,'/','Sender/u(t)'])
set_param([sys,'/','Sender/u(t)'],...
		'orientation',3,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[358,341,1280,441],...
		'position',[95,65,125,95])

add_block('built-in/Scope',[sys,'/','Sender/a(t)'])
set_param([sys,'/','Sender/a(t)'],...
		'orientation',3,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[358,417,1280,517],...
		'position',[180,65,210,95])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn1'])
set_param([sys,'/','Sender/Fcn1'],...
		'hide name',0,...
		'Expr','cos(4*pi*u)',...
		'position',[550,108,645,132])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn'])
set_param([sys,'/','Sender/Fcn'],...
		'hide name',0,...
		'Expr','abs(cos(1/2*pi*u-pi/2))',...
		'position',[410,69,490,101])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn3'])
set_param([sys,'/','Sender/Fcn3'],...
		'hide name',0,...
		'Expr','abs(cos(1/2*pi*u))',...
		'position',[410,164,490,196])

add_block('built-in/Clock',[sys,'/','Sender/Clock'])
set_param([sys,'/','Sender/Clock'],...
		'hide name',0,...
		'position',[355,125,375,145])

add_block('built-in/Product',[sys,'/','Sender/Product5'])
set_param([sys,'/','Sender/Product5'],...
		'hide name',0,...
		'position',[535,223,565,247])

add_block('built-in/Scope',[sys,'/','Sender/x_Q(t)'])
set_param([sys,'/','Sender/x_Q(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[358,667,1280,767],...
		'position',[565,185,595,215])

add_block('built-in/Transport Delay',[sys,'/',['Sender/Transport',13,'Delay']])
set_param([sys,'/',['Sender/Transport',13,'Delay']],...
		'hide name',0,...
		'Delay Time','.999',...
		'Buffer Size:','200',...
		'position',[275,215,315,245])

add_block('built-in/Switch',[sys,'/','Sender/Switch1'])
set_param([sys,'/','Sender/Switch1'],...
		'hide name',0,...
		'Threshold','1',...
		'position',[360,224,390,256])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn2'])
set_param([sys,'/','Sender/Fcn2'],...
		'hide name',0,...
		'Expr','sin(4*pi*u)',...
		'position',[550,143,645,167])

add_block('built-in/Product',[sys,'/','Sender/Product4'])
set_param([sys,'/','Sender/Product4'],...
		'hide name',0,...
		'position',[530,28,560,52])

add_block('built-in/Switch',[sys,'/','Sender/Switch2'])
set_param([sys,'/','Sender/Switch2'],...
		'hide name',0,...
		'Threshold','1',...
		'position',[365,19,395,51])

add_block('built-in/Transport Delay',[sys,'/',['Sender/Transport',13,'Delay1']])
set_param([sys,'/',['Sender/Transport',13,'Delay1']],...
		'hide name',0,...
		'Delay Time','.999',...
		'Buffer Size:','200',...
		'position',[275,30,315,60])

add_block('built-in/Sum',[sys,'/','Sender/Sum'])
set_param([sys,'/','Sender/Sum'],...
		'hide name',0,...
		'inputs','+-',...
		'position',[795,125,815,145])

add_block('built-in/Scope',[sys,'/','Sender/s_Q(t)'])
set_param([sys,'/','Sender/s_Q(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[358,754,1280,854],...
		'position',[810,215,840,245])

add_block('built-in/Scope',[sys,'/','Sender/s_I(t)'])
set_param([sys,'/','Sender/s_I(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[358,579,1280,679],...
		'position',[805,30,835,60])

add_block('built-in/Product',[sys,'/','Sender/Product3'])
set_param([sys,'/','Sender/Product3'],...
		'hide name',0,...
		'position',[715,33,745,57])


%     Subsystem  ['Sender/Pulse',13,'Generator1'].

new_system([sys,'/',['Sender/Pulse',13,'Generator1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],'Location',[158,441,759,682])

add_block('built-in/Outport',[sys,'/',['Sender/Pulse',13,'Generator1/out_1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])

add_block('built-in/Gain',[sys,'/',['Sender/Pulse',13,'Generator1/Gain']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Product',[sys,'/',['Sender/Pulse',13,'Generator1/Product']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Pulse',13,'Generator1/Logical',13,'Operator1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Pulse',13,'Generator1/Logical',13,'Operator']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Constant',[sys,'/',['Sender/Pulse',13,'Generator1/Constant1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Clock',[sys,'/',['Sender/Pulse',13,'Generator1/Clock1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Relational Operator',[sys,'/',['Sender/Pulse',13,'Generator1/Relational',13,'operator']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Sum',[sys,'/',['Sender/Pulse',13,'Generator1/Sum1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Sum',[sys,'/',['Sender/Pulse',13,'Generator1/Sum']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Constant',[sys,'/',['Sender/Pulse',13,'Generator1/Constant']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Pulse',13,'Generator1/Unit Delay']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Pulse',13,'Generator1/Unit Delay1']])
set_param([sys,'/',['Sender/Pulse',13,'Generator1/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[390,50;430,50;430,110;450,110])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[320,50;350,50])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[540,115;555,115])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[485,115;505,115])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[405,120;450,120])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[320,110;365,110])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[50,40;130,40])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[160,45;280,45])
add_line([sys,'/',['Sender/Pulse',13,'Generator1']],[155,130;245,130;245,55;280,55])
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'Mask Entries','2\/1\/1\/0\/')


%     Finished composite block ['Sender/Pulse',13,'Generator1'].

set_param([sys,'/',['Sender/Pulse',13,'Generator1']],...
		'hide name',0,...
		'position',[280,122,315,158])

add_block('built-in/Scope',[sys,'/','Sender/x_I(t)'])
set_param([sys,'/','Sender/x_I(t)'],...
		'orientation',1,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[358,492,1280,592],...
		'position',[560,60,590,90])

add_block('built-in/Product',[sys,'/','Sender/Product2'])
set_param([sys,'/','Sender/Product2'],...
		'hide name',0,...
		'position',[715,218,745,242])


%     Subsystem  'Sender/Doppelklick1'.

new_system([sys,'/','Sender/Doppelklick1'])
set_param([sys,'/','Sender/Doppelklick1'],'Location',[136,230,381,439])
set_param([sys,'/','Sender/Doppelklick1'],...
		'Mask Display','Schließe Sender',...
		'Mask Type','schließen')
set_param([sys,'/','Sender/Doppelklick1'],...
		'Mask Dialogue','eval(''close_system(''''msk/Sender'''');close_system(''''msk/Sender/u(t)'''');close_system(''''msk/Sender/a(t)'''');close_system(''''msk/Sender/x_I(t)'''');close_system(''''msk/Sender/s_I(t)'''');close_system(''''msk/Sender/x_Q(t)'''');close_system(''''msk/Sender/s_Q(t)'''');close_system(''''msk/Sender/s(t)'''');close_system(''''msk/Sender/phi(t)'''');'')')


%     Finished composite block 'Sender/Doppelklick1'.

set_param([sys,'/','Sender/Doppelklick1'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[855,20,990,46])

add_block('built-in/Outport',[sys,'/','Sender/Outport'])
set_param([sys,'/','Sender/Outport'],...
		'Port','2',...
		'position',[955,125,975,145])


%     Subsystem  ['Sender/Winkel-',13,'berechnung'].

new_system([sys,'/',['Sender/Winkel-',13,'berechnung']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung']],'Location',[0,0,359,206])

add_block('built-in/Note',[sys,'/',['Sender/Winkel-',13,'berechnung/Cartesian to Polar']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/Cartesian to Polar']],...
		'position',[165,30,170,35])

add_block('built-in/Outport',[sys,'/',['Sender/Winkel-',13,'berechnung/theta']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/theta']],...
		'Port','2',...
		'position',[295,130,315,150])

add_block('built-in/Inport',[sys,'/',['Sender/Winkel-',13,'berechnung/y']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/y']],...
		'Port','2',...
		'position',[20,129,40,151])

add_block('built-in/Inport',[sys,'/',['Sender/Winkel-',13,'berechnung/x']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/x']],...
		'position',[20,70,40,90])

add_block('built-in/Outport',[sys,'/',['Sender/Winkel-',13,'berechnung/r']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/r']],...
		'position',[295,75,315,95])

add_block('built-in/Mux',[sys,'/',['Sender/Winkel-',13,'berechnung/Mux']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/Mux']],...
		'inputs','2',...
		'position',[75,96,105,129])

add_block('built-in/Fcn',[sys,'/',['Sender/Winkel-',13,'berechnung/x->theta']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/x->theta']],...
		'Expr','atan2(u[2],u[1])',...
		'position',[160,129,265,151])

add_block('built-in/Fcn',[sys,'/',['Sender/Winkel-',13,'berechnung/x->r']])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung/x->r']],...
		'Expr','hypot(u[1],u[2])',...
		'position',[155,72,260,98])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[270,140;290,140])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[45,140;70,120])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[45,80;70,105])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[265,85;290,85])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[110,115;125,115;125,85;150,85])
add_line([sys,'/',['Sender/Winkel-',13,'berechnung']],[125,115;125,140;155,140])
set_param([sys,'/',['Sender/Winkel-',13,'berechnung']],...
		'Mask Display','plot(0,0,100,100,[24,20,15,20,20],[85,95,85,95,20],[80,20,95,85,95,85],[70,20,20,15,20,24],[56,56,55,52,50,46],[20,26,31,35,38,42])',...
		'Mask Type','[x,y]->[r,theta]')
set_param([sys,'/',['Sender/Winkel-',13,'berechnung']],...
		'Mask Dialogue','Tranformation from cartesian to polar\ncoordinates.\nr=sqrt(x^2+y^2), theta=atan(y/x)',...
		'Mask Help','Unmask this block for more help.')


%     Finished composite block ['Sender/Winkel-',13,'berechnung'].

set_param([sys,'/',['Sender/Winkel-',13,'berechnung']],...
		'position',[895,191,930,229])


%     Subsystem  'Sender/Diagramme'.

new_system([sys,'/','Sender/Diagramme'])
set_param([sys,'/','Sender/Diagramme'],'Location',[669,447,1065,724])

add_block('built-in/Switch',[sys,'/','Sender/Diagramme/Switch'])
set_param([sys,'/','Sender/Diagramme/Switch'],...
		'Threshold','1',...
		'position',[130,29,155,61])

add_block('built-in/Switch',[sys,'/','Sender/Diagramme/Switch1'])
set_param([sys,'/','Sender/Diagramme/Switch1'],...
		'Threshold','1',...
		'position',[130,84,155,116])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Inphase'])
set_param([sys,'/','Sender/Diagramme/Inphase'],...
		'position',[30,25,50,45])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Quadratur'])
set_param([sys,'/','Sender/Diagramme/Quadratur'],...
		'Port','2',...
		'position',[30,80,50,100])

add_block('built-in/Step Fcn',[sys,'/','Sender/Diagramme/Step input'])
set_param([sys,'/','Sender/Diagramme/Step input'],...
		'Time','starttime',...
		'position',[30,125,50,145])


%     Subsystem  'Sender/Diagramme/Signalraumpunkte'.

new_system([sys,'/','Sender/Diagramme/Signalraumpunkte'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Signalraumpunkte/Plot1'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Signalraumpunkte/in_1'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Sender/Diagramme/Signalraumpunkte'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block 'Sender/Diagramme/Signalraumpunkte'.

set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'position',[305,213,360,247])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux3'])
set_param([sys,'/','Sender/Diagramme/Mux3'],...
		'inputs','2',...
		'position',[230,211,265,244])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux2'])
set_param([sys,'/','Sender/Diagramme/Mux2'],...
		'inputs','2',...
		'position',[230,146,265,179])


%     Subsystem  'Sender/Diagramme/Trajektorie'.

new_system([sys,'/','Sender/Diagramme/Trajektorie'])
set_param([sys,'/','Sender/Diagramme/Trajektorie'],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Trajektorie/Plot1'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/Plot1'],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Trajektorie/Mux'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/Mux'],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Trajektorie/in_2'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/in_2'],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Trajektorie/in_1'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/in_1'],...
		'position',[15,55,35,75])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[105,90;125,90])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[45,125;50,125;60,95])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[40,65;45,65;45,80;60,80])
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block 'Sender/Diagramme/Trajektorie'.

set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'position',[305,155,360,190])

add_block('built-in/Constant',[sys,'/','Sender/Diagramme/Constant0'])
set_param([sys,'/','Sender/Diagramme/Constant0'],...
		'orientation',3,...
		'hide name',0,...
		'Value','0',...
		'position',[190,125,210,145])

add_block('built-in/Constant',[sys,'/','Sender/Diagramme/Constant'])
set_param([sys,'/','Sender/Diagramme/Constant'],...
		'orientation',3,...
		'hide name',0,...
		'Value','Inf',...
		'position',[90,125,110,145])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux1'])
set_param([sys,'/','Sender/Diagramme/Mux1'],...
		'inputs','2',...
		'position',[230,76,265,109])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux'])
set_param([sys,'/','Sender/Diagramme/Mux'],...
		'inputs','2',...
		'position',[230,21,265,54])


%     Subsystem  'Sender/Diagramme/Auge Inphase'.

new_system([sys,'/','Sender/Diagramme/Auge Inphase'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Auge Inphase/Plot1'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Auge Inphase/in_1'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Sender/Diagramme/Auge Inphase'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Sender/Diagramme/Auge Inphase'.

set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'position',[305,22,360,58])


%     Subsystem  'Sender/Diagramme/Auge Quadratur'.

new_system([sys,'/','Sender/Diagramme/Auge Quadratur'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Auge Quadratur/in_1'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Auge Quadratur/Plot1'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Sender/Diagramme/Auge Quadratur'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Sender/Diagramme/Auge Quadratur'.

set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'position',[305,77,360,113])
add_line([sys,'/','Sender/Diagramme'],[270,165;300,165])
add_line([sys,'/','Sender/Diagramme'],[270,230;300,230])
add_line([sys,'/','Sender/Diagramme'],[270,40;300,40])
add_line([sys,'/','Sender/Diagramme'],[270,95;300,95])
add_line([sys,'/','Sender/Diagramme'],[100,120;100,55;125,55])
add_line([sys,'/','Sender/Diagramme'],[100,110;125,110])
add_line([sys,'/','Sender/Diagramme'],[55,135;75,135;75,45;125,45])
add_line([sys,'/','Sender/Diagramme'],[75,100;125,100])
add_line([sys,'/','Sender/Diagramme'],[55,35;125,35])
add_line([sys,'/','Sender/Diagramme'],[55,90;125,90])
add_line([sys,'/','Sender/Diagramme'],[160,45;170,45;170,220;225,220])
add_line([sys,'/','Sender/Diagramme'],[170,155;225,155])
add_line([sys,'/','Sender/Diagramme'],[160,100;180,100;180,235;225,235])
add_line([sys,'/','Sender/Diagramme'],[180,170;225,170])
add_line([sys,'/','Sender/Diagramme'],[200,120;200,85;225,85])
add_line([sys,'/','Sender/Diagramme'],[200,85;200,30;225,30])
add_line([sys,'/','Sender/Diagramme'],[180,100;225,100])
add_line([sys,'/','Sender/Diagramme'],[170,45;225,45])
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','2D-Diagramme')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','1\/40\/0\/')


%     Finished composite block 'Sender/Diagramme'.

set_param([sys,'/','Sender/Diagramme'],...
		'position',[695,115,750,155])

add_block('built-in/Outport',[sys,'/','Sender/Binärsignal'])
set_param([sys,'/','Sender/Binärsignal'],...
		'Port','3',...
		'position',[100,10,120,30])

add_block('built-in/Scope',[sys,'/','Sender/phi(t)'])
set_param([sys,'/','Sender/phi(t)'],...
		'Vgain','3.141593',...
		'Hgain','25.000000',...
		'Vmax','6.283186',...
		'Hmax','50.000000',...
		'Window',[358,924,1280,1024],...
		'position',[960,220,990,250])

add_block('built-in/Outport',[sys,'/','Sender/Winkel'])
set_param([sys,'/','Sender/Winkel'],...
		'Port','4',...
		'position',[965,175,985,195])
add_line([sys,'/','Sender'],[820,135;950,135])
add_line([sys,'/','Sender'],[900,135;900,100])
add_line([sys,'/','Sender'],[750,45;800,45])
add_line([sys,'/','Sender'],[565,40;710,40])
add_line([sys,'/','Sender'],[750,230;805,230])
add_line([sys,'/','Sender'],[320,230;355,230])
add_line([sys,'/','Sender'],[175,130;235,130;235,25;360,25])
add_line([sys,'/','Sender'],[175,130;235,130;235,250;355,250])
add_line([sys,'/','Sender'],[260,250;270,230])
add_line([sys,'/','Sender'],[260,25;270,45])
add_line([sys,'/','Sender'],[380,135;390,135;390,180;405,180])
add_line([sys,'/','Sender'],[390,135;500,135;500,120;545,120])
add_line([sys,'/','Sender'],[500,135;500,155;545,155])
add_line([sys,'/','Sender'],[390,135;390,85;405,85])
add_line([sys,'/','Sender'],[400,35;525,35])
add_line([sys,'/','Sender'],[760,45;760,130;790,130])
add_line([sys,'/','Sender'],[395,240;530,240])
add_line([sys,'/','Sender'],[320,45;360,45])
add_line([sys,'/','Sender'],[495,85;505,85;505,45;525,45])
add_line([sys,'/','Sender'],[495,180;505,180;505,230;530,230])
add_line([sys,'/','Sender'],[650,120;655,120;655,50;710,50])
add_line([sys,'/','Sender'],[650,155;655,155;655,225;710,225])
add_line([sys,'/','Sender'],[570,235;710,235])
add_line([sys,'/','Sender'],[320,140;330,140;330,35;360,35])
add_line([sys,'/','Sender'],[330,140;330,240;355,240])
add_line([sys,'/','Sender'],[195,130;195,100])
add_line([sys,'/','Sender'],[575,40;575,55])
add_line([sys,'/','Sender'],[760,230;760,140;790,140])
add_line([sys,'/','Sender'],[670,235;670,145;690,145])
add_line([sys,'/','Sender'],[670,40;670,125;690,125])
add_line([sys,'/','Sender'],[55,130;135,130])
add_line([sys,'/','Sender'],[70,130;70,225;95,225])
add_line([sys,'/','Sender'],[110,130;110,100])
add_line([sys,'/','Sender'],[580,235;580,220])
add_line([sys,'/','Sender'],[670,180;855,180;855,220;890,220])
add_line([sys,'/','Sender'],[670,100;870,100;870,200;890,200])
add_line([sys,'/','Sender'],[55,105;70,105;70,20;95,20])
add_line([sys,'/','Sender'],[935,220;945,220;955,235])
add_line([sys,'/','Sender'],[945,220;945,185;960,185])


%     Finished composite block 'Sender'.

set_param([sys,'/','Sender'],...
		'position',[185,73,260,157])


%     Subsystem  'Doppelklick5'.

new_system([sys,'/','Doppelklick5'])
set_param([sys,'/','Doppelklick5'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick5'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Doppelklick5'.

set_param([sys,'/','Doppelklick5'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[440,50,575,76])

add_block('built-in/Scope',[sys,'/','s(t)'])
set_param([sys,'/','s(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','12.500000',...
		'Vmax','3.000000',...
		'Hmax','25.000000',...
		'Window',[360,540,1280,640])
open_system([sys,'/','s(t)'])
set_param([sys,'/','s(t)'],...
		'position',[390,25,420,55])

add_block('built-in/Scope',[sys,'/','r(t)'])
set_param([sys,'/','r(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','12.500000',...
		'Vmax','3.000000',...
		'Hmax','25.000000',...
		'Window',[360,640,1280,740])
open_system([sys,'/','r(t)'])
set_param([sys,'/','r(t)'],...
		'position',[590,25,620,55])
add_line(sys,[265,105;405,105;405,60])
add_line(sys,[550,105;640,105])
add_line(sys,[265,125;335,125;335,185;485,185;485,210])
add_line(sys,[265,85;335,85;335,60])
add_line(sys,[725,80;765,80;765,55])
add_line(sys,[725,125;765,125;765,185;525,185;525,210])
add_line(sys,[265,145;300,145;300,180])
add_line(sys,[405,105;460,105])
add_line(sys,[605,105;605,60])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
