function [ret,x0,str,ts,xts]=qpsnrzmf(t,x,u,flag);
%QPSNRZMF	is the M-file description of the SIMULINK system named QPSNRZMF.
%	The block-diagram can be displayed by typing: QPSNRZMF.
%
%	SYS=QPSNRZMF(T,X,U,FLAG) returns depending on FLAG certain
%	system values given time point, T, current state vector, X,
%	and input vector, U.
%	FLAG is used to indicate the type of output to be returned in SYS.
%
%	Setting FLAG=1 causes QPSNRZMF to return state derivatives, FLAG=2
%	discrete states, FLAG=3 system outputs and FLAG=4 next sample
%	time. For more information and other options see SFUNC.
%
%	Calling QPSNRZMF with a FLAG of zero:
%	[SIZES]=QPSNRZMF([],[],[],0),  returns a vector, SIZES, which
%	contains the sizes of the state vector and other parameters.
%		SIZES(1) number of states
%		SIZES(2) number of discrete states
%		SIZES(3) number of outputs
%		SIZES(4) number of inputs
%		SIZES(5) number of roots (currently unsupported)
%		SIZES(6) direct feedthrough flag
%		SIZES(7) number of sample times
%
%	For the definition of other parameters in SIZES, see SFUNC.
%	See also, TRIM, LINMOD, LINSIM, EULER, RK23, RK45, ADAMS, GEAR.

% Note: This M-file is only used for saving graphical information;
%       after the model is loaded into memory an internal model
%       representation is used.

% the system will take on the name of this mfile:
sys = mfilename;
new_system(sys)
simver(1.3)
if (0 == (nargin + nargout))
     set_param(sys,'Location',[251,42,1260,320])
     open_system(sys)
end;
set_param(sys,'algorithm',     'RK-45')
set_param(sys,'Start time',    '0.0')
set_param(sys,'Stop time',     '999999')
set_param(sys,'Min step size', '0.000001')
set_param(sys,'Max step size', '10')
set_param(sys,'Relative error','1e-6')
set_param(sys,'Return vars',   '')


%     Subsystem  'Empfänger'.

new_system([sys,'/','Empfänger'])
set_param([sys,'/','Empfänger'],'Location',[251,42,1259,320])

add_block('built-in/Product',[sys,'/','Empfänger/Product'])
set_param([sys,'/','Empfänger/Product'],...
		'hide name',0,...
		'position',[300,74,330,101])

add_block('built-in/Scope',[sys,'/','Empfänger/x_eI(t)'])
set_param([sys,'/','Empfänger/x_eI(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[0,440,640,540],...
		'position',[350,20,380,50])

add_block('built-in/Fcn',[sys,'/','Empfänger/Fcn'])
set_param([sys,'/','Empfänger/Fcn'],...
		'hide name',0,...
		'Expr','2*cos(4*pi*u)',...
		'position',[185,119,265,141])

add_block('built-in/Fcn',[sys,'/','Empfänger/Fcn1'])
set_param([sys,'/','Empfänger/Fcn1'],...
		'hide name',0,...
		'Expr','-2*sin(4*pi*u)',...
		'position',[185,159,265,181])

add_block('built-in/Scope',[sys,'/','Empfänger/x_eQ(t)'])
set_param([sys,'/','Empfänger/x_eQ(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[640,440,1280,540],...
		'position',[350,155,380,185])

add_block('built-in/Clock',[sys,'/','Empfänger/Clock'])
set_param([sys,'/','Empfänger/Clock'],...
		'hide name',0,...
		'position',[145,140,165,160])

add_block('built-in/Product',[sys,'/','Empfänger/Product1'])
set_param([sys,'/','Empfänger/Product1'],...
		'hide name',0,...
		'position',[295,213,325,237])

add_block('built-in/Inport',[sys,'/',['Empfänger/gestörtes',13,'QPSK-',13,'Signal']])
set_param([sys,'/',['Empfänger/gestörtes',13,'QPSK-',13,'Signal']],...
		'position',[25,145,45,165])

add_block('built-in/Scope',[sys,'/','Empfänger/d_eI(t)'])
set_param([sys,'/','Empfänger/d_eI(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[0,540,640,640],...
		'position',[540,20,570,50])

add_block('built-in/Scope',[sys,'/','Empfänger/d_eQ(t)'])
set_param([sys,'/','Empfänger/d_eQ(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[640,540,1280,640],...
		'position',[540,155,570,185])


%     Subsystem  ['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)'].

new_system([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],'Location',[96,182,645,417])

add_block('built-in/Constant',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/imag_pt']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/imag_pt']],...
		'BackGround',5,...
		'Value','y2',...
		'position',[165,169,190,191])

add_block('built-in/Constant',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/real_pt']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/real_pt']],...
		'BackGround',3,...
		'Value','y1',...
		'position',[170,84,195,106])

add_block('built-in/Outport',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/out_1']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/out_1']],...
		'position',[495,85,515,105])

add_block('built-in/S-Function',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Minimum1']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Minimum1']],...
		'function name','arymimai',...
		'parameters','''min''',...
		'position',[415,85,475,105])

add_block('built-in/Sum',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum2']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum2']],...
		'position',[370,78,390,107])

add_block('built-in/Product',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Product1']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Product1']],...
		'position',[300,130,325,150])

add_block('built-in/Product',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Product']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Product']],...
		'position',[300,45,325,65])

add_block('built-in/Sum',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum6']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum6']],...
		'ForeGround',4,...
		'inputs','+-',...
		'position',[230,123,250,152])

add_block('built-in/Sum',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum1']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Sum1']],...
		'ForeGround',2,...
		'inputs','+-',...
		'position',[230,38,250,67])

add_block('built-in/Zero-Order Hold',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Zero-Order',13,'Hold1']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Zero-Order',13,'Hold1']],...
		'ForeGround',4,...
		'Sample time','td',...
		'position',[120,114,155,146])

add_block('built-in/Inport',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/imag']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/imag']],...
		'Port','2',...
		'position',[45,120,65,140])

add_block('built-in/Inport',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/real']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/real']],...
		'position',[45,35,65,55])

add_block('built-in/Zero-Order Hold',[sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Zero-Order',13,'Hold']])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)/Zero-Order',13,'Hold']],...
		'ForeGround',2,...
		'Sample time','td',...
		'position',[120,29,155,61])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[480,95;490,95])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[395,95;410,95])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[330,140;340,140;340,100;365,100])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[330,55;340,55;340,85;365,85])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[255,140;270,140;270,135;295,135])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[270,140;270,145;295,145])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[255,55;270,55;270,50;295,50])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[270,55;270,60;295,60])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[195,180;205,180;205,145;225,145])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[160,130;225,130])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[160,45;225,45])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[200,95;205,95;205,60;225,60])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[70,130;115,130])
add_line([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],[70,45;115,45])
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'Mask Display','QASK\nC-demap',...
		'Mask Type','QASK C-demap')
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'Mask Dialogue','Reverse the QASK map. Input in-phase\nand quadrature components from the\ntwo inputs. Output demapped signal.|Number of symbols on each circle NIC::|Radii for each circle RIC:|Phase shift on each circle PIC (rad):|Symbol interval and offset (sec):')
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'Mask Translate','N=@1;A=@2;P=@3;td=@4;y1=apkconst(N,A,P);y2=imag(y1);y1=real(y1);')
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'Mask Help','This block demaps a QASK mapped signal using circle constellation. You can place this block after a QAM demodulation block. The circle constellation is defined in NIC, RIC, and PIC. The symbol interval can be a two elements vector with the first element being offset. The default offset is zero. Use function MODMAP to view the constellation.')
set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'Mask Entries','[4]\/[sqrt(2)]\/[pi/4]\/1\/')


%     Finished composite block ['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)'].

set_param([sys,'/',['Empfänger/Signalraum-',13,'decodierung',13,'(Symbolentscheider)']],...
		'position',[800,128,880,172])

add_block('built-in/Scope',[sys,'/','Empfänger/r(t)'])
set_param([sys,'/','Empfänger/r(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[320,340,960,440],...
		'position',[60,70,90,100])

add_block('built-in/Outport',[sys,'/',['Empfänger/empfangenes',13,'Symbol']])
set_param([sys,'/',['Empfänger/empfangenes',13,'Symbol']],...
		'position',[950,140,970,160])


%     Subsystem  'Empfänger/Doppelklick4'.

new_system([sys,'/','Empfänger/Doppelklick4'])
set_param([sys,'/','Empfänger/Doppelklick4'],'Location',[136,230,381,439])
set_param([sys,'/','Empfänger/Doppelklick4'],...
		'Mask Display','Schließe Empfänger',...
		'Mask Type','schließen',...
		'Mask Dialogue','eval(''closempf'')')


%     Finished composite block 'Empfänger/Doppelklick4'.

set_param([sys,'/','Empfänger/Doppelklick4'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[815,20,950,46])

add_block('built-in/Scope',[sys,'/','Empfänger/v(t)'])
set_param([sys,'/','Empfänger/v(t)'],...
		'orientation',3,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[320,740,960,840],...
		'position',[895,70,925,100])

add_block('built-in/S-Function',[sys,'/','Empfänger/Integrate and Dump_'])
set_param([sys,'/','Empfänger/Integrate and Dump_'],...
		'function name','schdint',...
		'parameters','td, ts, limit',...
		'Mask Display','Scheduled\nreset-int',...
		'Mask Type','Scheduled reset integration')
set_param([sys,'/','Empfänger/Integrate and Dump_'],...
		'Mask Dialogue','Reset the state to be zero(s) at the\nscheduled reset sample point.|Scheduled reset time interval and offset (sec):|Computation sample time and offset (sec):|Modulo bound:')
set_param([sys,'/','Empfänger/Integrate and Dump_'],...
		'Mask Translate','td=@1;ts=@2;limit=@3;')
set_param([sys,'/','Empfänger/Integrate and Dump_'],...
		'Mask Help','This block resets the state(s) to be zero(s) at the reset time points. The reset interval can be a two-element vector with the second element as offset. The computation sample time must be smaller than the reset interval. The block resets the state value to be the remainder of the state divided by the modulo bound when the absolute value of the state is larger than the modulo bound.')
set_param([sys,'/','Empfänger/Integrate and Dump_'],...
		'Mask Entries','1\/.01\/999\/',...
		'position',[425,203,505,247])

add_block('built-in/S-Function',[sys,'/','Empfänger/Integrate and Dump'])
set_param([sys,'/','Empfänger/Integrate and Dump'],...
		'function name','schdint',...
		'parameters','td, ts, limit',...
		'Mask Display','Scheduled\nreset-int',...
		'Mask Type','Scheduled reset integration')
set_param([sys,'/','Empfänger/Integrate and Dump'],...
		'Mask Dialogue','Reset the state to be zero(s) at the\nscheduled reset sample point.|Scheduled reset time interval and offset (sec):|Computation sample time and offset (sec):|Modulo bound:')
set_param([sys,'/','Empfänger/Integrate and Dump'],...
		'Mask Translate','td=@1;ts=@2;limit=@3;')
set_param([sys,'/','Empfänger/Integrate and Dump'],...
		'Mask Help','This block resets the state(s) to be zero(s) at the reset time points. The reset interval can be a two-element vector with the second element as offset. The computation sample time must be smaller than the reset interval. The block resets the state value to be the remainder of the state divided by the modulo bound when the absolute value of the state is larger than the modulo bound.')
set_param([sys,'/','Empfänger/Integrate and Dump'],...
		'Mask Entries','1\/.01\/999\/',...
		'position',[425,68,505,112])


%     Subsystem  'Empfänger/Diagramme'.

new_system([sys,'/','Empfänger/Diagramme'])
set_param([sys,'/','Empfänger/Diagramme'],'Location',[669,447,1065,724])


%     Subsystem  'Empfänger/Diagramme/Auge Quadratur'.

new_system([sys,'/','Empfänger/Diagramme/Auge Quadratur'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Auge Quadratur/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Auge Quadratur/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Empfänger/Diagramme/Auge Quadratur'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Empfänger/Diagramme/Auge Quadratur'.

set_param([sys,'/','Empfänger/Diagramme/Auge Quadratur'],...
		'position',[305,77,360,113])


%     Subsystem  'Empfänger/Diagramme/Auge Inphase'.

new_system([sys,'/','Empfänger/Diagramme/Auge Inphase'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Auge Inphase/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Auge Inphase/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Auge Inphase'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Empfänger/Diagramme/Auge Inphase'.

set_param([sys,'/','Empfänger/Diagramme/Auge Inphase'],...
		'position',[305,22,360,58])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux'])
set_param([sys,'/','Empfänger/Diagramme/Mux'],...
		'inputs','2',...
		'position',[230,21,265,54])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux1'])
set_param([sys,'/','Empfänger/Diagramme/Mux1'],...
		'inputs','2',...
		'position',[230,76,265,109])

add_block('built-in/Constant',[sys,'/','Empfänger/Diagramme/Constant'])
set_param([sys,'/','Empfänger/Diagramme/Constant'],...
		'orientation',3,...
		'hide name',0,...
		'Value','Inf',...
		'position',[90,125,110,145])

add_block('built-in/Constant',[sys,'/','Empfänger/Diagramme/Constant0'])
set_param([sys,'/','Empfänger/Diagramme/Constant0'],...
		'orientation',3,...
		'hide name',0,...
		'Value','0',...
		'position',[190,125,210,145])


%     Subsystem  'Empfänger/Diagramme/Trajektorie'.

new_system([sys,'/','Empfänger/Diagramme/Trajektorie'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Trajektorie/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/in_1'],...
		'position',[15,55,35,75])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Trajektorie/in_2'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/in_2'],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Trajektorie/Mux'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/Mux'],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Trajektorie/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie/Plot1'],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[40,65;45,65;45,80;60,80])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[45,125;50,125;60,95])
add_line([sys,'/','Empfänger/Diagramme/Trajektorie'],[105,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block 'Empfänger/Diagramme/Trajektorie'.

set_param([sys,'/','Empfänger/Diagramme/Trajektorie'],...
		'position',[305,155,360,190])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux2'])
set_param([sys,'/','Empfänger/Diagramme/Mux2'],...
		'inputs','2',...
		'position',[230,146,265,179])

add_block('built-in/Mux',[sys,'/','Empfänger/Diagramme/Mux3'])
set_param([sys,'/','Empfänger/Diagramme/Mux3'],...
		'inputs','2',...
		'position',[230,211,265,244])


%     Subsystem  'Empfänger/Diagramme/Signalraumpunkte'.

new_system([sys,'/','Empfänger/Diagramme/Signalraumpunkte'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],'Location',[165,242,460,428])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Signalraumpunkte/in_1'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Empfänger/Diagramme/Signalraumpunkte/Plot1'])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],[100,90;125,90])
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block 'Empfänger/Diagramme/Signalraumpunkte'.

set_param([sys,'/','Empfänger/Diagramme/Signalraumpunkte'],...
		'position',[305,213,360,247])

add_block('built-in/Step Fcn',[sys,'/','Empfänger/Diagramme/Step input'])
set_param([sys,'/','Empfänger/Diagramme/Step input'],...
		'Time','starttime',...
		'position',[30,125,50,145])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Quadratur'])
set_param([sys,'/','Empfänger/Diagramme/Quadratur'],...
		'Port','2',...
		'position',[30,80,50,100])

add_block('built-in/Inport',[sys,'/','Empfänger/Diagramme/Inphase'])
set_param([sys,'/','Empfänger/Diagramme/Inphase'],...
		'position',[30,25,50,45])

add_block('built-in/Switch',[sys,'/','Empfänger/Diagramme/Switch1'])
set_param([sys,'/','Empfänger/Diagramme/Switch1'],...
		'Threshold','1',...
		'position',[130,84,155,116])

add_block('built-in/Switch',[sys,'/','Empfänger/Diagramme/Switch'])
set_param([sys,'/','Empfänger/Diagramme/Switch'],...
		'Threshold','1',...
		'position',[130,29,155,61])
add_line([sys,'/','Empfänger/Diagramme'],[160,45;170,45;170,220;225,220])
add_line([sys,'/','Empfänger/Diagramme'],[170,45;225,45])
add_line([sys,'/','Empfänger/Diagramme'],[160,100;180,100;180,235;225,235])
add_line([sys,'/','Empfänger/Diagramme'],[180,100;225,100])
add_line([sys,'/','Empfänger/Diagramme'],[200,120;200,85;225,85])
add_line([sys,'/','Empfänger/Diagramme'],[200,85;200,30;225,30])
add_line([sys,'/','Empfänger/Diagramme'],[180,170;225,170])
add_line([sys,'/','Empfänger/Diagramme'],[170,155;225,155])
add_line([sys,'/','Empfänger/Diagramme'],[55,90;125,90])
add_line([sys,'/','Empfänger/Diagramme'],[55,35;125,35])
add_line([sys,'/','Empfänger/Diagramme'],[55,135;75,135;75,45;125,45])
add_line([sys,'/','Empfänger/Diagramme'],[75,100;125,100])
add_line([sys,'/','Empfänger/Diagramme'],[100,120;100,55;125,55])
add_line([sys,'/','Empfänger/Diagramme'],[100,110;125,110])
add_line([sys,'/','Empfänger/Diagramme'],[270,95;300,95])
add_line([sys,'/','Empfänger/Diagramme'],[270,40;300,40])
add_line([sys,'/','Empfänger/Diagramme'],[270,230;300,230])
add_line([sys,'/','Empfänger/Diagramme'],[270,165;300,165])
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','2D-Diagramme')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/','Empfänger/Diagramme'],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','0\/40\/0\/')


%     Finished composite block 'Empfänger/Diagramme'.

set_param([sys,'/','Empfänger/Diagramme'],...
		'position',[675,10,730,50])


%     Subsystem  ['Empfänger/Schwellenwert-',13,'Entscheider'].

new_system([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],'Location',[159,417,467,586])

add_block('built-in/Outport',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/out_1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/out_1']],...
		'position',[265,70,285,90])

add_block('built-in/Inport',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/in_1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/in_1']],...
		'position',[35,30,55,50])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Relational',13,'Operator']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Relational',13,'Operator']],...
		'Operator','>',...
		'position',[140,32,170,63])

add_block('built-in/Sum',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Sum']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Sum']],...
		'inputs','+-',...
		'position',[215,64,235,91])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Relational',13,'Operator1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Relational',13,'Operator1']],...
		'Operator','<',...
		'position',[140,92,170,123])

add_block('built-in/Constant',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Constant']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider/Constant']],...
		'Value','0',...
		'position',[65,105,85,125])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[60,40;135,40])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[95,40;95,100;135,100])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[90,115;135,115])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[110,115;110,55;135,55])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[175,110;185,110;185,85;210,85])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[175,50;185,50;185,70;210,70])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],[240,80;260,80])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],...
		'Mask Display','plot(-50,-50,50,50,[-50,50],[0,0],[0,0],[-50,50],[-40,0],[-30,-30],[0,40],[30,30])',...
		'Mask Type','Sign',...
		'Mask Dialogue','y = sign(x)')
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],...
		'Mask Help','Sign Function:\n\t\t\ty = 1 if x > 0\n\t\t\ty = 0 if x = 0\n\t\t\ty = -1 if x < 0')


%     Finished composite block ['Empfänger/Schwellenwert-',13,'Entscheider'].

set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider']],...
		'position',[690,77,720,103])


%     Subsystem  ['Empfänger/Schwellenwert-',13,'Entscheider_'].

new_system([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],'Location',[159,417,467,586])

add_block('built-in/Constant',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Constant']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Constant']],...
		'Value','0',...
		'position',[65,105,85,125])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Relational',13,'Operator1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Relational',13,'Operator1']],...
		'Operator','<',...
		'position',[140,92,170,123])

add_block('built-in/Sum',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Sum']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Sum']],...
		'inputs','+-',...
		'position',[215,64,235,91])

add_block('built-in/Relational Operator',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Relational',13,'Operator']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/Relational',13,'Operator']],...
		'Operator','>',...
		'position',[140,32,170,63])

add_block('built-in/Inport',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/in_1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/in_1']],...
		'position',[35,30,55,50])

add_block('built-in/Outport',[sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/out_1']])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_/out_1']],...
		'position',[265,70,285,90])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[240,80;260,80])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[175,50;185,50;185,70;210,70])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[175,110;185,110;185,85;210,85])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[90,115;135,115])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[110,115;110,55;135,55])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[60,40;135,40])
add_line([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],[95,40;95,100;135,100])
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],...
		'Mask Display','plot(-50,-50,50,50,[-50,50],[0,0],[0,0],[-50,50],[-40,0],[-30,-30],[0,40],[30,30])',...
		'Mask Type','Sign',...
		'Mask Dialogue','y = sign(x)')
set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],...
		'Mask Help','Sign Function:\n\t\t\ty = 1 if x > 0\n\t\t\ty = 0 if x = 0\n\t\t\ty = -1 if x < 0')


%     Finished composite block ['Empfänger/Schwellenwert-',13,'Entscheider_'].

set_param([sys,'/',['Empfänger/Schwellenwert-',13,'Entscheider_']],...
		'position',[690,212,720,238])

add_block('built-in/Scope',[sys,'/','Empfänger/v_eI(t)'])
set_param([sys,'/','Empfänger/v_eI(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[0,640,640,740],...
		'position',[810,75,840,105])

add_block('built-in/Scope',[sys,'/','Empfänger/v_eQ(t)'])
set_param([sys,'/','Empfänger/v_eQ(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[640,640,1280,740],...
		'position',[810,225,840,255])


%     Subsystem  'Empfänger/Doppelklick5'.

new_system([sys,'/','Empfänger/Doppelklick5'])
set_param([sys,'/','Empfänger/Doppelklick5'],'Location',[136,230,381,439])
set_param([sys,'/','Empfänger/Doppelklick5'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Empfänger/Doppelklick5'.

set_param([sys,'/','Empfänger/Doppelklick5'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[10,240,145,266])
add_line([sys,'/','Empfänger'],[170,150;180,130])
add_line([sys,'/','Empfänger'],[50,155;75,155;75,105])
add_line([sys,'/','Empfänger'],[170,150;180,170])
add_line([sys,'/','Empfänger'],[270,170;280,170;290,220])
add_line([sys,'/','Empfänger'],[270,130;280,130;280,95;295,95])
add_line([sys,'/','Empfänger'],[75,155;120,155;120,80;295,80])
add_line([sys,'/','Empfänger'],[120,155;120,230;290,230])
add_line([sys,'/','Empfänger'],[885,150;945,150])
add_line([sys,'/','Empfänger'],[910,150;910,105])
add_line([sys,'/','Empfänger'],[330,225;420,225])
add_line([sys,'/','Empfänger'],[365,225;365,190])
add_line([sys,'/','Empfänger'],[510,225;555,225;555,190])
add_line([sys,'/','Empfänger'],[335,90;420,90])
add_line([sys,'/','Empfänger'],[365,90;365,55])
add_line([sys,'/','Empfänger'],[510,90;555,90;555,55])
add_line([sys,'/','Empfänger'],[510,225;650,225;650,40;670,40])
add_line([sys,'/','Empfänger'],[510,90;625,90;625,20;670,20])
add_line([sys,'/','Empfänger'],[645,225;685,225])
add_line([sys,'/','Empfänger'],[725,225;760,225;760,160;795,160])
add_line([sys,'/','Empfänger'],[625,90;685,90])
add_line([sys,'/','Empfänger'],[725,90;755,90;755,140;795,140])
add_line([sys,'/','Empfänger'],[755,90;805,90])
add_line([sys,'/','Empfänger'],[760,225;760,240;805,240])


%     Finished composite block 'Empfänger'.

set_param([sys,'/','Empfänger'],...
		'position',[650,62,725,148])

add_block('built-in/Scope',[sys,'/',['gesendetes',13,'Symbol']])
set_param([sys,'/',['gesendetes',13,'Symbol']],...
		'orientation',1,...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[360,440,1280,540])
open_system([sys,'/',['gesendetes',13,'Symbol']])
set_param([sys,'/',['gesendetes',13,'Symbol']],...
		'position',[320,220,350,250])


%     Subsystem  'Kanal'.

new_system([sys,'/','Kanal'])
set_param([sys,'/','Kanal'],'Location',[11,262,273,408])


%     Subsystem  ['Kanal/Gaussian noise',13,'generator'].

new_system([sys,'/',['Kanal/Gaussian noise',13,'generator']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],'Location',[22,119,370,243])

add_block('built-in/Outport',[sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/out_1']],...
		'position',[285,60,305,80])

add_block('built-in/Sum',[sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Sum']],...
		'position',[220,60,240,80])

add_block('built-in/Constant',[sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Constant']],...
		'Value','m',...
		'position',[140,20,160,40])

add_block('built-in/White Noise',[sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Random',13,'Number']],...
		'Seed','s',...
		'position',[35,57,80,93])

add_block('built-in/State-Space',[sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'A','[]',...
		'B','[]',...
		'C','[]',...
		'D','K',...
		'Mask Display','K',...
		'Mask Type','Matrix Gain',...
		'Mask Dialogue','Matrix Gain.|Gain matrix:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'Mask Translate','K = @1;',...
		'Mask Help','Multiplies input vector by entered matrix to produce output vector (y=Au).',...
		'Mask Entries','d\/')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator/Matrix',13,'Gain']],...
		'position',[140,61,165,89])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[85,75;135,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[170,75;215,75])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[245,70;280,70])
add_line([sys,'/',['Kanal/Gaussian noise',13,'generator']],[165,30;190,30;190,65;215,65])
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Display','plot(0,0,100,100,x,y);Gaussian',...
		'Mask Type','Gaussian noise generator')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Dialogue','Generate Gaussian distributed noise with\ngiven mean and variance value.|Mean value:|Variance (vector or matrix):|Initial seed:')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=srcsicon(3);')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Help','When the mean value and seed are vectors, the output of this block is a vector. The length of the vector is the same as the length of the mean value vector or the length of the seed. When the variance entry is a vector, the variance is a diagonal matrix.')
set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'Mask Entries','m\/d\/s\/')


%     Finished composite block ['Kanal/Gaussian noise',13,'generator'].

set_param([sys,'/',['Kanal/Gaussian noise',13,'generator']],...
		'position',[25,48,105,92])

add_block('built-in/Sum',[sys,'/','Kanal/Sum'])
set_param([sys,'/','Kanal/Sum'],...
		'position',[150,55,170,75])

add_block('built-in/Outport',[sys,'/','Kanal/out_1'])
set_param([sys,'/','Kanal/out_1'],...
		'position',[200,55,220,75])

add_block('built-in/Inport',[sys,'/','Kanal/in_1'])
set_param([sys,'/','Kanal/in_1'],...
		'position',[45,10,65,30])
add_line([sys,'/','Kanal'],[110,70;145,70])
add_line([sys,'/','Kanal'],[70,20;115,20;115,60;145,60])
add_line([sys,'/','Kanal'],[175,65;195,65])
set_param([sys,'/','Kanal'],...
		'Mask Display','plot(0,0,100,100,x,y);AWGN',...
		'Mask Type','AWGN channel, fixed parameter')
set_param([sys,'/','Kanal'],...
		'Mask Dialogue','Additive white Gaussian noise channel\nwith fixed mean and variance.|Mean value:|Variance (std^2):|Initial Seed:',...
		'Mask Translate','m=@1;d=@2;s=@3;[m,d,s]=gwnoise(m,d,s);[x,y]=chanicon;')
set_param([sys,'/','Kanal'],...
		'Mask Help','This block adds white Gaussian noise to the input signal. The mean and the variance can be a scalar or vector with the same length as the input signal.',...
		'Mask Entries','0\/.001\/12345\/')


%     Finished composite block 'Kanal'.

set_param([sys,'/','Kanal'],...
		'position',[465,83,545,127])


%     Subsystem  'Error rate'.

new_system([sys,'/','Error rate'])
set_param([sys,'/','Error rate'],'Location',[255,368,509,510])

add_block('built-in/S-Function',[sys,'/','Error rate/S-function'])
set_param([sys,'/','Error rate/S-function'],...
		'function name','sbiterr',...
		'parameters','num_lin, K, TDelay, Sample',...
		'position',[130,52,195,78])

add_block('built-in/Mux',[sys,'/','Error rate/Mux'])
set_param([sys,'/','Error rate/Mux'],...
		'inputs','2',...
		'position',[65,46,100,79])

add_block('built-in/Inport',[sys,'/','Error rate/in_1'])
set_param([sys,'/','Error rate/in_1'],...
		'position',[15,45,35,65])

add_block('built-in/Inport',[sys,'/','Error rate/in_2'])
set_param([sys,'/','Error rate/in_2'],...
		'Port','2',...
		'position',[15,60,35,80])
add_line([sys,'/','Error rate'],[105,65;125,65])
add_line([sys,'/','Error rate'],[40,55;60,55])
add_line([sys,'/','Error rate'],[40,70;60,70])
set_param([sys,'/','Error rate'],...
		'Mask Display','Error\nmeter',...
		'Mask Type','Symbol/bit error counter')
set_param([sys,'/','Error rate'],...
		'Mask Dialogue','Use the input data from the 1st port as the reference signal to detect the number of errors and error rate of the 2nd signal.|Bit per symbol:|Number of digits on display:|Delay between 1st port and 2nd port:|Sample time (sec):')
set_param([sys,'/','Error rate'],...
		'Mask Translate','K=@1;num_lin=@2;TDelay=@3;Sample=@4;')
set_param([sys,'/','Error rate'],...
		'Mask Help','The signal from the first port must be a scalar. The second input port can be a vector with a delay to the first port signal. The comparison happens only at the sampling point.')
set_param([sys,'/','Error rate'],...
		'Mask Entries','2\/10\/1\/1\/')


%     Finished composite block 'Error rate'.

set_param([sys,'/','Error rate'],...
		'orientation',1,...
		'position',[465,215,545,255])

add_block('built-in/Scope',[sys,'/',['empfangenes',13,'Symbol']])
set_param([sys,'/',['empfangenes',13,'Symbol']],...
		'orientation',1,...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[360,738,1280,838])
open_system([sys,'/',['empfangenes',13,'Symbol']])
set_param([sys,'/',['empfangenes',13,'Symbol']],...
		'position',[745,220,775,250])

add_block('built-in/Scope',[sys,'/','Binärsignal'])
set_param([sys,'/','Binärsignal'],...
		'orientation',3,...
		'move name',0,...
		'Vgain','3.000000',...
		'Hgain','25.000000',...
		'Vmax','6.000000',...
		'Hmax','50.000000',...
		'Window',[360,341,1280,441])
open_system([sys,'/','Binärsignal'])
set_param([sys,'/','Binärsignal'],...
		'position',[320,25,350,55])


%     Subsystem  'Sender'.

new_system([sys,'/','Sender'])
set_param([sys,'/','Sender'],'Location',[252,42,1260,321])

add_block('built-in/Scope',[sys,'/','Sender/x_I(t)'])
set_param([sys,'/','Sender/x_I(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,438,1280,538],...
		'position',[430,10,460,40])

add_block('built-in/Scope',[sys,'/','Sender/d_I(t)'])
set_param([sys,'/','Sender/d_I(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,340,1280,440],...
		'position',[220,10,250,40])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn1'])
set_param([sys,'/','Sender/Fcn1'],...
		'hide name',0,...
		'Expr','cos(4*pi*u)',...
		'position',[615,130,710,160])

add_block('built-in/Product',[sys,'/','Sender/Product'])
set_param([sys,'/','Sender/Product'],...
		'hide name',0,...
		'position',[770,83,800,107])


%     Subsystem  ['Sender/Signalraum-',13,'zuordnung'].

new_system([sys,'/',['Sender/Signalraum-',13,'zuordnung']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],'Location',[58,103,403,268])

add_block('built-in/Zero-Order Hold',[sys,'/',['Sender/Signalraum-',13,'zuordnung/Zero-Order',13,'Hold1']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/Zero-Order',13,'Hold1']],...
		'Sample time','td',...
		'position',[80,14,115,46])

add_block('built-in/Inport',[sys,'/',['Sender/Signalraum-',13,'zuordnung/in_1']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/in_1']],...
		'position',[25,20,45,40])

add_block('built-in/Look Up Table',[sys,'/',['Sender/Signalraum-',13,'zuordnung/real part']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/real part']],...
		'Input_Values','x',...
		'Output_Values','y1',...
		'position',[180,17,215,43])

add_block('built-in/Look Up Table',[sys,'/',['Sender/Signalraum-',13,'zuordnung/imag part1']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/imag part1']],...
		'Input_Values','x',...
		'Output_Values','y2',...
		'position',[175,97,210,123])

add_block('built-in/Outport',[sys,'/',['Sender/Signalraum-',13,'zuordnung/Real']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/Real']],...
		'position',[275,20,295,40])

add_block('built-in/Outport',[sys,'/',['Sender/Signalraum-',13,'zuordnung/Imag']])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung/Imag']],...
		'Port','2',...
		'position',[275,100,295,120])
add_line([sys,'/',['Sender/Signalraum-',13,'zuordnung']],[50,30;75,30])
add_line([sys,'/',['Sender/Signalraum-',13,'zuordnung']],[120,30;175,30])
add_line([sys,'/',['Sender/Signalraum-',13,'zuordnung']],[145,30;145,110;170,110])
add_line([sys,'/',['Sender/Signalraum-',13,'zuordnung']],[220,30;270,30])
add_line([sys,'/',['Sender/Signalraum-',13,'zuordnung']],[215,110;270,110])
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'Mask Display','QASK\nC-map',...
		'Mask Type','QASK C-map')
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'Mask Dialogue','QASK mapping with circle constellation. The constellation is defined in NIC, RIC and PIC.|Number of symbols in each circle NIC:|Radii in each circle RIC:|Phase shift in each circle PIC (rad):|Symbol interval and offset (sec):')
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'Mask Translate','N=@1;A=@2;P=@3;td=@4;y1=apkconst(N,A,P);y1=[y1;y1];y1=y1(:);y2=imag(y1);y1=real(y1);x=[-sum(N) 1:sum(N)-1;1:sum(N)-1 10*sum(N)]-.5;x=x(:);')
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'Mask Help','This block maps a digital signal onto in-phase and quadratic components, which are outputs in the first and second output port respectively. The circle constellation is defined in NIC, RIC, and PIC. The input symbol interval can be a two-element vector with the second element being offset. The default value offset is 0. Use the MODMAP function to see the constellation.')
set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'Mask Entries','[4]\/[sqrt(2)]\/[pi/4]\/1\/')


%     Finished composite block ['Sender/Signalraum-',13,'zuordnung'].

set_param([sys,'/',['Sender/Signalraum-',13,'zuordnung']],...
		'position',[110,113,190,157])

add_block('built-in/Product',[sys,'/','Sender/Product1'])
set_param([sys,'/','Sender/Product1'],...
		'hide name',0,...
		'position',[770,233,800,257])

add_block('built-in/Sum',[sys,'/','Sender/Sum'])
set_param([sys,'/','Sender/Sum'],...
		'hide name',0,...
		'inputs','+-',...
		'position',[880,155,900,175])

add_block('built-in/Clock',[sys,'/','Sender/Clock'])
set_param([sys,'/','Sender/Clock'],...
		'position',[555,155,575,175])

add_block('built-in/Fcn',[sys,'/','Sender/Fcn2'])
set_param([sys,'/','Sender/Fcn2'],...
		'hide name',0,...
		'Expr','sin(4*pi*u)',...
		'position',[615,175,710,205])

add_block('built-in/Scope',[sys,'/','Sender/d_Q(t)'])
set_param([sys,'/','Sender/d_Q(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,633,1280,733],...
		'position',[220,165,250,195])

add_block('built-in/Scope',[sys,'/','Sender/x_Q(t)'])
set_param([sys,'/','Sender/x_Q(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,731,1280,831],...
		'position',[425,165,455,195])

add_block('built-in/Scope',[sys,'/','Sender/s_Q(t)'])
set_param([sys,'/','Sender/s_Q(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,827,1280,927],...
		'position',[865,230,895,260])

add_block('built-in/Scope',[sys,'/','Sender/s(t)'])
set_param([sys,'/','Sender/s(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,924,1280,1024],...
		'position',[920,80,950,110])


%     Subsystem  'Sender/Doppelklick1'.

new_system([sys,'/','Sender/Doppelklick1'])
set_param([sys,'/','Sender/Doppelklick1'],'Location',[136,230,381,439])
set_param([sys,'/','Sender/Doppelklick1'],...
		'Mask Display','Schließe Sender',...
		'Mask Type','schließen',...
		'Mask Dialogue','eval(''clossend'')')


%     Finished composite block 'Sender/Doppelklick1'.

set_param([sys,'/','Sender/Doppelklick1'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[785,20,920,46])

add_block('built-in/Outport',[sys,'/',['Sender/QPSK-',13,'Signal']])
set_param([sys,'/',['Sender/QPSK-',13,'Signal']],...
		'Port','2',...
		'position',[965,155,985,175])

add_block('built-in/Outport',[sys,'/','Sender/Symboltakt'])
set_param([sys,'/','Sender/Symboltakt'],...
		'Port','4',...
		'position',[110,205,130,225])

add_block('built-in/Outport',[sys,'/','Sender/Bitstrom'])
set_param([sys,'/','Sender/Bitstrom'],...
		'position',[110,15,130,35])

add_block('built-in/Outport',[sys,'/','Sender/Symbol'])
set_param([sys,'/','Sender/Symbol'],...
		'Port','3',...
		'position',[110,60,130,80])

add_block('built-in/Scope',[sys,'/','Sender/s_I(t)'])
set_param([sys,'/','Sender/s_I(t)'],...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[359,536,1280,636],...
		'position',[865,80,895,110])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],'Location',[84,708,621,947])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Takt']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Takt']],...
		'Port','3',...
		'position',[480,195,500,215])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Binär']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Binär']],...
		'position',[480,60,500,80])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Symbol']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Symbol']],...
		'Port','2',...
		'position',[480,140,500,160])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],'Location',[355,528,737,675])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],'Location',[55,192,283,286])

add_block('built-in/S-Function',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1/S-function1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1/S-function1']],...
		'function name','homopuls',...
		'parameters','samp_time, out_divid, offset',...
		'position',[40,31,105,59])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1/Outport']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1/Outport']],...
		'position',[160,35,180,55])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],[110,45;155,45])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Display','Vector\nPulse',...
		'Mask Type','Pulse generator')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Dialogue','Vector pulses with sample rate of each pulse as Sample_time ./Divider. |Sample time (scalar, sec):|Divider (integer vector):|Offset (have same dimension as Divider:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Translate','samp_time=@1;out_divid=@2;offset=@3;')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Help','This block generator a vector pulses. The output length is the same as the vector defined in "Divider". The ith element of the output has the sample time Sample_time/Divider(i). All elements in "Divider" must be integers.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'Mask Entries','ts\/1\/off\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Pulses deivide',13,'same sample time1']],...
		'position',[50,56,110,94])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/out_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/out_1']],...
		'position',[295,65,315,85])

add_block('built-in/S-Function',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'BackGround',5,...
		'function name','trigwksp',...
		'parameters','var,thd,cyclFlag,ini',...
		'Mask Display','Triggered\nread')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'Mask Type','Read from workspace')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'Mask Dialogue','The raising edge of input pulse trigger the block output the next row from the workspace variable.|Read the variable:|Threshold for the input pulse:|Cyclic read variable (1) or amend zeros (0).|Output before first trigger:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'Mask Translate','var=@1;thd=@2;cyclFlag=@3;ini=@4;')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'Mask Help','This block reads the data from a workspace variable. The output is refreshed at the raising edge of the input pulse.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom/Message source']],...
		'Mask Entries','var\/.1\/cyc\/ini\/',...
		'position',[180,53,255,97])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],[260,75;290,75])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],[115,75;175,75])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'Mask Display','plot(0,0,100,100,x,y);Rd wksp',...
		'Mask Type','Read from workspace')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'Mask Dialogue','Read from a workspace variable at\nsampling time point.|Variable (column_number=block_output_length):|Data output sample time (sec):|Repeat flag (1: repeat read, 0: output zeros after eof).|Initial output:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'Mask Translate','var=@1;td=@2;ts=td(1);if (length(td)>=2),off=td(2);else off=0;end;cyc=@3;ini=@4;[x,y]=srcsicon(7);')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'Mask Help','This block reads from a workspace variable at a given sample time. The column number is the block output vector length. When the simulation reaches the end of the variable (eof), the block will cyclically output from the first row of the variable or output zeros based on the repeat flag entree.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'Mask Entries','randint(2000,1,2)\/.5\/1\/1\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Bitstrom']],...
		'position',[25,48,85,92])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],'Location',[158,441,759,682])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Unit Delay1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Unit Delay1']],...
		'orientation',2,...
		'Sample time','[Ts,st2]',...
		'x0','ini',...
		'position',[140,165,190,185])

add_block('built-in/Unit Delay',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Unit Delay']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Unit Delay']],...
		'orientation',2,...
		'Sample time','[Ts,st1]',...
		'position',[145,75,195,95])

add_block('built-in/Constant',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Constant']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Constant']],...
		'position',[25,30,45,50])

add_block('built-in/Sum',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Sum']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Sum']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[135,35,155,55])

add_block('built-in/Sum',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Sum1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Sum1']],...
		'hide name',0,...
		'inputs','+-',...
		'position',[130,120,150,140])

add_block('built-in/Relational Operator',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Relational',13,'operator']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Relational',13,'operator']],...
		'hide name',0,...
		'position',[370,102,400,133])

add_block('built-in/Clock',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Clock1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Clock1']],...
		'hide name',0,...
		'position',[295,100,315,120])

add_block('built-in/Constant',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Constant1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Constant1']],...
		'Value','stt',...
		'position',[295,149,320,171])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Logical',13,'Operator']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Logical',13,'Operator']],...
		'Operator','XOR',...
		'position',[285,38,315,62])

add_block('built-in/Logical Operator',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Logical',13,'Operator1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Logical',13,'Operator1']],...
		'Operator','NOT',...
		'Number of Input Ports','1',...
		'position',[355,38,385,62])

add_block('built-in/Product',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Product']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Product']],...
		'hide name',0,...
		'position',[455,105,480,125])

add_block('built-in/Gain',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Gain']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/Gain']],...
		'hide name',0,...
		'Gain','ht',...
		'position',[510,102,535,128])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/out_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber/out_1']],...
		'hide name',0,...
		'position',[560,105,580,125])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[155,130;245,130;245,55;280,55])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[160,45;280,45])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[50,40;70,40;70,125;125,125])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[135,175;100,175;100,135;125,135])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[155,130;210,130;210,175;195,175])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[50,40;130,40])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[160,45;230,45;230,85;200,85])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[140,85;105,85;105,50;130,50])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[320,110;365,110])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[405,120;450,120])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[485,115;505,115])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[540,115;555,115])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[325,160;345,160;345,125;365,125])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[320,50;350,50])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],[390,50;430,50;430,110;450,110])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'Mask Display','plot(0,0,100,100,[90,75,75,60,60,35,35,20,20,10],[20,20,80,80,20,20,80,80,20,20])',...
		'Mask Type','Pulse Generator')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'Mask Dialogue','Pulse Generator.|Pulse period (secs):|Pulse width:|Pulse height:|Pulse start time:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'Mask Translate','Ts=@1; du=@2; ht=@3; stt=@4; ini=ones(length(ht),1); st1=rem(stt,Ts); st2=rem(stt+du,Ts);if(Ts<=1.2*du),ini=zeros(length(ht),1);end;')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'Mask Help','Pulse generator which ensures pulse\ntransitions are hit. Provides a vector of pulses when the height is entered as a vector.\nUnmask to see how it works.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'Mask Entries','.5\/.25\/1\/0\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Taktgeber']],...
		'position',[35,147,70,183])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],'Location',[19,610,374,740])

add_block('built-in/Demux',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/Demux']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/Demux']],...
		'outputs','[len_rg, 1]',...
		'position',[260,55,300,90])

add_block('built-in/S-Function',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/S-function']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/S-function']],...
		'function name','regshift',...
		'parameters','shft_out, thrhld',...
		'position',[150,65,200,85])

add_block('built-in/Mux',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/Mux']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/Mux']],...
		'inputs','2',...
		'position',[80,56,115,89])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/out_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/out_1']],...
		'position',[330,55,350,75])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/out_2']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/out_2']],...
		'Port','2',...
		'position',[330,70,350,90])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/in_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/in_1']],...
		'position',[30,55,50,75])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/in_2']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister/in_2']],...
		'Port','2',...
		'position',[30,70,50,90])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[120,75;145,75])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[205,75;255,75])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[305,65;325,65])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[305,80;325,80])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[55,65;75,65])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],[55,80;75,80])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);Reg. shift',...
		'Mask Type','Register-shift')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'Mask Dialogue','The rising edge of the 2nd port pulse\ntriggers the block to input the 1st port data and to shift the register.|Delay steps (output length is same as this vector size):|Threshold in detecting the rising edge of the pulse:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'Mask Translate','shft_out=@1;thrhld=@2;len_rg=length(@1);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);[x,y]=trigicon(1,75,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'Mask Help','This block stores the scalar input signal from the 1st input port at the rising edge of the pulse from the 2nd port. The 1st outport outputs a vector with its size the same as the "Delay steps" entree of this block. The maximum delay is the register size of this block. The second outport outputs a positive pulse when the register is\nrefreshed.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'Mask Entries','[2 1]\/1\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Schieberegister']],...
		'position',[120,133,200,177])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],'Location',[22,58,460,228])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_3']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_3']],...
		'Port','3',...
		'position',[65,85,85,105])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_2']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_2']],...
		'Port','2',...
		'position',[40,70,60,90])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/in_1']],...
		'position',[15,55,35,75])

add_block('built-in/S-Function',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/S-function']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/S-function']],...
		'function name','regdown',...
		'parameters','ini_idx, idx_inc, thrshld, cycl_flag',...
		'position',[185,70,235,90])

add_block('built-in/Demux',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/Demux']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/Demux']],...
		'outputs','[out_size 1]',...
		'position',[290,62,330,98])

add_block('built-in/Mux',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/Mux']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/Mux']],...
		'inputs','[in_size 1 1]',...
		'position',[110,59,140,101])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/out_2']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/out_2']],...
		'Port','2',...
		'position',[355,80,375,100])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/out_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe/out_1']],...
		'position',[390,60,410,80])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[90,95;105,95])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[335,90;350,90])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[65,80;105,80])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[335,70;385,70])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[40,65;105,65])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[145,80;180,80])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],[240,80;285,80])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'Mask Display','plot(0,0,100,100,x,y,v,w,u,z);Buffer dwn',...
		'Mask Type','Triggered buffer down')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'Mask Dialogue','Rising edge of the 2nd port triggers 1st port vector signal in. Rising edge of the 3rd port triggers 1st outport signal out.|Input signal vector size:|Initial index (integer vector):|Increment for each index (integer vector):|Trigger threshold:|When index exceed register size, 1: cyclic out, 0: zero out:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'Mask Translate','in_size=@1;ini_idx=@2;idx_inc=@3;thrshld=@4;cycl_flag=@5;out_size=length(ini_idx);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);[x,y]=trigicon(1,75,get_param(gcb,''orientation''),2);[u,z]=trigicon(0,50,get_param(gcb,''orientation''),2);')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'Mask Help','The block refreshes its registers with the vector input from the 1st inport at the rising edge of the 2nd inport pulse. The 1st outport outputs the elements of the registers starting with the given initial index. The rising edge of the 3rd inport pulse triggers the 1st output to output the register value with the index increasing the increment value. The second outport outputs a spike pulse when the internal register is refreshed.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'Mask Entries','2\/[1 0]\/[0 0]\/1\/0\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Haltestufe']],...
		'position',[260,138,340,182])

add_block('built-in/S-Function',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']],...
		'function name','simbi2de',...
		'parameters','p',...
		'Mask Display','Vec to sca\nconverter',...
		'Mask Type','Base M vector to decimal integer')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']],...
		'Mask Dialogue','Convert base M integer with each\nposition in the input vector into scalar decimal output.|Input integer base M:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']],...
		'Mask Translate','p=@1;')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']],...
		'Mask Help','This block convert the base M vector into scalar decimal integer output. Each element of the input vector is one position of the digit of the base M integer. The 1st element in the input vector contains the 1''s position. The 2nd element in the input vector contains the M''s position.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/D//A Wandlung']],...
		'Mask Entries','2\/',...
		'position',[370,128,450,172])


%     Subsystem  ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung'].

new_system([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],'Location',[12,432,357,702])

add_block('built-in/Relational Operator',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Relational',13,'Operator']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Relational',13,'Operator']],...
		'position',[150,168,180,192])

add_block('built-in/Constant',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Constant1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Constant1']],...
		'Value','n*ts(1)+ts(2)',...
		'position',[15,194,100,216])

add_block('built-in/Constant',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Constant']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Constant']],...
		'Value','ini',...
		'position',[120,230,140,250])

add_block('built-in/Switch',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Switch']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Switch']],...
		'Threshold','.1',...
		'position',[270,114,295,146])

add_block('built-in/Filter',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/K-step',13,'delay']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/K-step',13,'delay']],...
		'Numerator','[zeros(1,n), 1]',...
		'Denominator','1',...
		'Sample time','ts',...
		'position',[60,70,185,110])

add_block('built-in/Outport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/out_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/out_1']],...
		'position',[325,120,345,140])

add_block('built-in/Inport',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/in_1']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/in_1']],...
		'position',[20,80,40,100])

add_block('built-in/Digital Clock',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Digital Clock']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung/Digital Clock']],...
		'Sample time','ts',...
		'position',[60,140,95,170])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[185,180;220,180;220,130;265,130])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[105,205;115,205;115,185;145,185])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[100,155;115,155;115,175;145,175])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[145,240;240,240;240,140;265,140])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[190,90;195,90;195,120;265,120])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[45,90;55,90])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],[300,130;320,130])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'Mask Display','    -k\nz   ',...
		'Mask Type','Multi-step delay')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'Mask Dialogue','Output is K-step delay of the input signal.|Delay steps (integer):|Sample time (sec):|Initial output:')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'Mask Translate','n=@1;ts=@2;if length(ts)<2, ts=[ts 0];end;ini=@3;')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'Mask Help','This block holds the input signal for K steps and then outputs the signal. The delay step cannot be changed during the simulation.')
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'Mask Entries','2\/.5\/0\/')


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Verzögerung']],...
		'position',[260,48,340,92])

add_block('built-in/Note',[sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Jeweils zwei Bits des Bitstroms werden zu einem quaternären Symbol decodiert.',13,'Reihenfolge der Bits: Zuerst MSB, dann LSB.']])
set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK/Jeweils zwei Bits des Bitstroms werden zu einem quaternären Symbol decodiert.',13,'Reihenfolge der Bits: Zuerst MSB, dann LSB.']],...
		'position',[265,0,270,5])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[345,170;355,170;355,205;475,205])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[455,150;475,150])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[345,70;475,70])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[205,145;255,145])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[345,150;365,150])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[75,165;115,165])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[205,165;225,165;225,160;255,160])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[225,165;225,175;255,175])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[90,70;255,70])
add_line([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],[105,70;115,145])


%     Finished composite block ['Sender/Quaternäre',13,'Quelle',13,'für QPSK'].

set_param([sys,'/',['Sender/Quaternäre',13,'Quelle',13,'für QPSK']],...
		'position',[25,109,55,161])


%     Subsystem  'Sender/Diagramme'.

new_system([sys,'/','Sender/Diagramme'])
set_param([sys,'/','Sender/Diagramme'],'Location',[669,447,1065,724])

add_block('built-in/Switch',[sys,'/','Sender/Diagramme/Switch'])
set_param([sys,'/','Sender/Diagramme/Switch'],...
		'Threshold','1',...
		'position',[130,29,155,61])

add_block('built-in/Switch',[sys,'/','Sender/Diagramme/Switch1'])
set_param([sys,'/','Sender/Diagramme/Switch1'],...
		'Threshold','1',...
		'position',[130,84,155,116])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Inphase'])
set_param([sys,'/','Sender/Diagramme/Inphase'],...
		'position',[30,25,50,45])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Quadratur'])
set_param([sys,'/','Sender/Diagramme/Quadratur'],...
		'Port','2',...
		'position',[30,80,50,100])

add_block('built-in/Step Fcn',[sys,'/','Sender/Diagramme/Step input'])
set_param([sys,'/','Sender/Diagramme/Step input'],...
		'Time','starttime',...
		'position',[30,125,50,145])


%     Subsystem  'Sender/Diagramme/Signalraumpunkte'.

new_system([sys,'/','Sender/Diagramme/Signalraumpunkte'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Signalraumpunkte/Plot1'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Signalraumpunkte/in_1'])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Sender/Diagramme/Signalraumpunkte'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'Mask Entries','[1 .5 .999]\/[-1.5 1.5]\/0\/0\/''y.''\/[.5 offset]\/')


%     Finished composite block 'Sender/Diagramme/Signalraumpunkte'.

set_param([sys,'/','Sender/Diagramme/Signalraumpunkte'],...
		'position',[305,213,360,247])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux3'])
set_param([sys,'/','Sender/Diagramme/Mux3'],...
		'inputs','2',...
		'position',[230,211,265,244])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux2'])
set_param([sys,'/','Sender/Diagramme/Mux2'],...
		'inputs','2',...
		'position',[230,146,265,179])


%     Subsystem  'Sender/Diagramme/Trajektorie'.

new_system([sys,'/','Sender/Diagramme/Trajektorie'])
set_param([sys,'/','Sender/Diagramme/Trajektorie'],'Location',[165,242,460,428])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Trajektorie/Plot1'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/Plot1'],...
		'function name','eyediasi',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Trajektorie/Mux'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/Mux'],...
		'inputs','2',...
		'position',[65,70,100,105])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Trajektorie/in_2'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/in_2'],...
		'Port','2',...
		'position',[20,115,40,135])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Trajektorie/in_1'])
set_param([sys,'/','Sender/Diagramme/Trajektorie/in_1'],...
		'position',[15,55,35,75])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[105,90;125,90])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[45,125;50,125;60,95])
add_line([sys,'/','Sender/Diagramme/Trajektorie'],[40,65;45,65;45,80;60,80])
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Display','plot(0,0,100,100,x,y,v,w);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Dialogue','Produce eye-pattern diagram/scatter\nplot/x-y plot with the rising edge of the second input as the decision line.|Eye-pattern plot time frame:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Line-type for x-y plot (0 for no plot):')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);[v,w]=trigicon(0,25,get_param(gcb,''orientation''),2);')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Help','This plot opens one, two, or three plots by assigning the line type parameters. The scatter plot point is selected by the rising edge of a trigger signal. A decision line is drawn at the rising edge of the trigger signal.')
set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'Mask Entries','[2 0 1]\/[-1.5 1.5]\/0\/0\/0\/''g-''\/')


%     Finished composite block 'Sender/Diagramme/Trajektorie'.

set_param([sys,'/','Sender/Diagramme/Trajektorie'],...
		'position',[305,155,360,190])

add_block('built-in/Constant',[sys,'/','Sender/Diagramme/Constant0'])
set_param([sys,'/','Sender/Diagramme/Constant0'],...
		'orientation',3,...
		'hide name',0,...
		'Value','0',...
		'position',[190,125,210,145])

add_block('built-in/Constant',[sys,'/','Sender/Diagramme/Constant'])
set_param([sys,'/','Sender/Diagramme/Constant'],...
		'orientation',3,...
		'hide name',0,...
		'Value','Inf',...
		'position',[90,125,110,145])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux1'])
set_param([sys,'/','Sender/Diagramme/Mux1'],...
		'inputs','2',...
		'position',[230,76,265,109])

add_block('built-in/Mux',[sys,'/','Sender/Diagramme/Mux'])
set_param([sys,'/','Sender/Diagramme/Mux'],...
		'inputs','2',...
		'position',[230,21,265,54])


%     Subsystem  'Sender/Diagramme/Auge Inphase'.

new_system([sys,'/','Sender/Diagramme/Auge Inphase'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],'Location',[121,409,416,595])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Auge Inphase/Plot1'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Auge Inphase/in_1'])
set_param([sys,'/','Sender/Diagramme/Auge Inphase/in_1'],...
		'position',[75,80,95,100])
add_line([sys,'/','Sender/Diagramme/Auge Inphase'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Sender/Diagramme/Auge Inphase'.

set_param([sys,'/','Sender/Diagramme/Auge Inphase'],...
		'position',[305,22,360,58])


%     Subsystem  'Sender/Diagramme/Auge Quadratur'.

new_system([sys,'/','Sender/Diagramme/Auge Quadratur'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],'Location',[121,409,416,595])

add_block('built-in/Inport',[sys,'/','Sender/Diagramme/Auge Quadratur/in_1'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur/in_1'],...
		'position',[75,80,95,100])

add_block('built-in/S-Function',[sys,'/','Sender/Diagramme/Auge Quadratur/Plot1'])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur/Plot1'],...
		'function name','eyesampl',...
		'parameters','time_range, boundary, kept_length, eye_line, scatter_line, two_d_line',...
		'position',[130,70,200,110])
add_line([sys,'/','Sender/Diagramme/Auge Quadratur'],[100,90;125,90])
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Display','plot(0,0,100,100,x,y);',...
		'Mask Type','Eye-diagram/scatter plot')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Dialogue','Produce eye-pattern diagram and/or scatter plot.|[Symbol interval, plot offset, decision point offset]:|Lower and upper bound of in-coming signal (1x2 vector):|Number of saved traces:|Line-type for eye-pattern diagram (0 for no plot):|Line-type for scatter plot (0 for no plot):|Plot update sample time:')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Translate','time_range=@1;boundary=@2;kept_length=@3;eye_line=@4;scatter_line=@5;two_d_line=@6;[x,y]=srcsicon(10);')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Help','This plot opens one, or two plots by assigning the line type parameters. The scatter plot point is selected by the decision point in the first parameter entry. A decision line is drawn in the eye-pattern diagram. The plot is updated at the plot update sample time point.')
set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'Mask Entries','[2 0 1+offset]\/[-1.5 1.5]\/0\/''w-/r-''\/0\/2/anzahl\/')


%     Finished composite block 'Sender/Diagramme/Auge Quadratur'.

set_param([sys,'/','Sender/Diagramme/Auge Quadratur'],...
		'position',[305,77,360,113])
add_line([sys,'/','Sender/Diagramme'],[270,165;300,165])
add_line([sys,'/','Sender/Diagramme'],[270,230;300,230])
add_line([sys,'/','Sender/Diagramme'],[270,40;300,40])
add_line([sys,'/','Sender/Diagramme'],[270,95;300,95])
add_line([sys,'/','Sender/Diagramme'],[100,120;100,55;125,55])
add_line([sys,'/','Sender/Diagramme'],[100,110;125,110])
add_line([sys,'/','Sender/Diagramme'],[55,135;75,135;75,45;125,45])
add_line([sys,'/','Sender/Diagramme'],[75,100;125,100])
add_line([sys,'/','Sender/Diagramme'],[55,35;125,35])
add_line([sys,'/','Sender/Diagramme'],[55,90;125,90])
add_line([sys,'/','Sender/Diagramme'],[160,45;170,45;170,220;225,220])
add_line([sys,'/','Sender/Diagramme'],[170,155;225,155])
add_line([sys,'/','Sender/Diagramme'],[160,100;180,100;180,235;225,235])
add_line([sys,'/','Sender/Diagramme'],[180,170;225,170])
add_line([sys,'/','Sender/Diagramme'],[200,120;200,85;225,85])
add_line([sys,'/','Sender/Diagramme'],[200,85;200,30;225,30])
add_line([sys,'/','Sender/Diagramme'],[180,100;225,100])
add_line([sys,'/','Sender/Diagramme'],[170,45;225,45])
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Display','plot(0,0,100,100,x,y)',...
		'Mask Type','2D-Diagramme')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Dialogue','Augendiagramm, Trajektorie und\nSignalraumpunkte.|Startzeit für Plot:|Abtastwerte pro Zeitfenster (2*TS):|Offset der Entscheiderlinie zur Mitte:')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Translate','starttime = @1;  anzahl = @2; offset = @3; [x, y] = srcsicon(10);')
set_param([sys,'/','Sender/Diagramme'],...
		'Mask Help','Dieser Block stellt die Augendiagramme, Trajektorien,\nund Signalraumpunkte auf der Sende- oder Empfangsseite dar',...
		'Mask Entries','0\/40\/0\/')


%     Finished composite block 'Sender/Diagramme'.

set_param([sys,'/','Sender/Diagramme'],...
		'position',[570,10,625,50])
add_line([sys,'/','Sender'],[195,145;205,145;205,250;765,250])
add_line([sys,'/','Sender'],[235,250;235,200])
add_line([sys,'/','Sender'],[60,135;105,135])
add_line([sys,'/','Sender'],[805,245;860,245])
add_line([sys,'/','Sender'],[835,245;835,170;875,170])
add_line([sys,'/','Sender'],[805,95;860,95])
add_line([sys,'/','Sender'],[835,95;835,160;875,160])
add_line([sys,'/','Sender'],[195,125;205,125;205,90;765,90])
add_line([sys,'/','Sender'],[445,90;445,45])
add_line([sys,'/','Sender'],[440,250;440,200])
add_line([sys,'/','Sender'],[510,90;510,20;565,20])
add_line([sys,'/','Sender'],[535,250;535,40;565,40])
add_line([sys,'/','Sender'],[580,165;590,165;590,190;610,190])
add_line([sys,'/','Sender'],[580,165;590,165;590,145;610,145])
add_line([sys,'/','Sender'],[715,145;735,145;735,100;765,100])
add_line([sys,'/','Sender'],[715,190;735,190;735,240;765,240])
add_line([sys,'/','Sender'],[60,150;80,150;80,215;105,215])
add_line([sys,'/','Sender'],[905,165;935,165;935,115])
add_line([sys,'/','Sender'],[935,165;960,165])
add_line([sys,'/','Sender'],[80,135;80,70;105,70])
add_line([sys,'/','Sender'],[60,120;65,120;65,25;105,25])
add_line([sys,'/','Sender'],[235,90;235,45])


%     Finished composite block 'Sender'.

set_param([sys,'/','Sender'],...
		'position',[200,72,275,158])


%     Subsystem  'Doppelklick2'.

new_system([sys,'/','Doppelklick2'])
set_param([sys,'/','Doppelklick2'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick2'],...
		'Mask Display','Zeige Sender',...
		'Mask Type','öffnen',...
		'Mask Dialogue','eval(''showsend'')')


%     Finished composite block 'Doppelklick2'.

set_param([sys,'/','Doppelklick2'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[30,85,165,111])


%     Subsystem  'Doppelklick3'.

new_system([sys,'/','Doppelklick3'])
set_param([sys,'/','Doppelklick3'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick3'],...
		'Mask Display','Zeige Empfänger',...
		'Mask Type','öffnen',...
		'Mask Dialogue','eval(''showempf'')')


%     Finished composite block 'Doppelklick3'.

set_param([sys,'/','Doppelklick3'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[800,85,935,111])


%     Subsystem  'Signalraumkonstellation_'.

new_system([sys,'/','Signalraumkonstellation_'])
set_param([sys,'/','Signalraumkonstellation_'],'Location',[0,38,1264,980])
set_param([sys,'/','Signalraumkonstellation_'],...
		'Mask Display','Signalraum\nKonstellation',...
		'Mask Dialogue','eval(''figure''); eval(''modmap(''''qask/cir'''',4,sqrt(2),pi/4)'')')


%     Finished composite block 'Signalraumkonstellation_'.

set_param([sys,'/','Signalraumkonstellation_'],...
		'BackGround',7,...
		'hide name',0,...
		'position',[55,20,140,56])

add_block('built-in/Scope',[sys,'/','s(t)'])
set_param([sys,'/','s(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[360,538,1280,638])
open_system([sys,'/','s(t)'])
set_param([sys,'/','s(t)'],...
		'position',[385,25,415,55])

add_block('built-in/Scope',[sys,'/','r(t)'])
set_param([sys,'/','r(t)'],...
		'orientation',3,...
		'Vgain','1.500000',...
		'Hgain','25.000000',...
		'Vmax','3.000000',...
		'Hmax','50.000000',...
		'Window',[360,638,1280,738])
open_system([sys,'/','r(t)'])
set_param([sys,'/','r(t)'],...
		'position',[585,25,615,55])


%     Subsystem  'Doppelklick5'.

new_system([sys,'/','Doppelklick5'])
set_param([sys,'/','Doppelklick5'],'Location',[136,230,381,439])
set_param([sys,'/','Doppelklick5'],...
		'Mask Display','Rauschen einstellen',...
		'Mask Type','rauschen',...
		'Mask Dialogue','eval(''setnoise'')')


%     Finished composite block 'Doppelklick5'.

set_param([sys,'/','Doppelklick5'],...
		'BackGround',7,...
		'hide name',0,...
		'Font Angle','italic',...
		'position',[440,50,575,76])
add_line(sys,[280,105;400,105;400,60])
add_line(sys,[280,125;335,125;335,215])
add_line(sys,[280,85;335,85;335,60])
add_line(sys,[400,105;460,105])
add_line(sys,[550,105;645,105])
add_line(sys,[730,105;760,105;760,215])
add_line(sys,[760,185;525,185;525,210])
add_line(sys,[335,185;485,185;485,210])
add_line(sys,[600,105;600,60])

drawnow

% Return any arguments.
if (nargin | nargout)
	% Must use feval here to access system in memory
	if (nargin > 3)
		if (flag == 0)
			eval(['[ret,x0,str,ts,xts]=',sys,'(t,x,u,flag);'])
		else
			eval(['ret =', sys,'(t,x,u,flag);'])
		end
	else
		[ret,x0,str,ts,xts] = feval(sys);
	end
else
	drawnow % Flash up the model and execute load callback
end
