function [golddata]=goldPN(pntaps1,pntaps2,pninitial)
% pntaps1=[1 1 0 1 1];%反馈线的状态c1-cn
%pninitial=[zeros(1,length(pntaps1)-1),1];%寄存器的初始状态
%N=2^length(pntaps1)-1;%N表示扩频码的长度
feedback=rem((pninitial*pntaps1'),2);
pninitial=[feedback,pninitial(1,1:length(pntaps1)-1)];
sqn1=mPN(pntaps1,pninitial);%sqn1表示扩频码,大小为N*N的矩阵
pninitial2=[zeros(1,length(pntaps1)-1),1];
sqn2=mPN(pntaps2,pninitial2);%C表示扩频码,大小为1*N的矩阵
golddata=rem((sqn1+sqn2),2);
